/*
SpedV API

Testing SimRailAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/NiklasSchmitt/spedv-go-sdk"
)

func Test_openapi_SimRailAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SimRailAPIService V1SimrailServerGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SimRailAPI.V1SimrailServerGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimRailAPIService V1SimrailServerIdDispatchstationsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.SimRailAPI.V1SimrailServerIdDispatchstationsGet(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimRailAPIService V1SimrailServerIdDispatchstationsNameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var name string

		resp, httpRes, err := apiClient.SimRailAPI.V1SimrailServerIdDispatchstationsNameGet(context.Background(), id, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimRailAPIService V1SimrailServerIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.SimRailAPI.V1SimrailServerIdGet(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimRailAPIService V1SimrailServerIdTrainsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.SimRailAPI.V1SimrailServerIdTrainsGet(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimRailAPIService V1SimrailServerIdTrainsNumberGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var number string

		resp, httpRes, err := apiClient.SimRailAPI.V1SimrailServerIdTrainsNumberGet(context.Background(), id, number).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
