/*
SpedV API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FPHSpedVAPIObjectsMoneyMoneyTransferDay type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FPHSpedVAPIObjectsMoneyMoneyTransferDay{}

// FPHSpedVAPIObjectsMoneyMoneyTransferDay struct for FPHSpedVAPIObjectsMoneyMoneyTransferDay
type FPHSpedVAPIObjectsMoneyMoneyTransferDay struct {
	Day time.Time `json:"day"`
	Income float64 `json:"income"`
	Outgo float64 `json:"outgo"`
	Bilance float64 `json:"bilance"`
	Currency NullableString `json:"currency"`
}

type _FPHSpedVAPIObjectsMoneyMoneyTransferDay FPHSpedVAPIObjectsMoneyMoneyTransferDay

// NewFPHSpedVAPIObjectsMoneyMoneyTransferDay instantiates a new FPHSpedVAPIObjectsMoneyMoneyTransferDay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFPHSpedVAPIObjectsMoneyMoneyTransferDay(day time.Time, income float64, outgo float64, bilance float64, currency NullableString) *FPHSpedVAPIObjectsMoneyMoneyTransferDay {
	this := FPHSpedVAPIObjectsMoneyMoneyTransferDay{}
	this.Day = day
	this.Income = income
	this.Outgo = outgo
	this.Bilance = bilance
	this.Currency = currency
	return &this
}

// NewFPHSpedVAPIObjectsMoneyMoneyTransferDayWithDefaults instantiates a new FPHSpedVAPIObjectsMoneyMoneyTransferDay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFPHSpedVAPIObjectsMoneyMoneyTransferDayWithDefaults() *FPHSpedVAPIObjectsMoneyMoneyTransferDay {
	this := FPHSpedVAPIObjectsMoneyMoneyTransferDay{}
	return &this
}

// GetDay returns the Day field value
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) GetDay() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Day
}

// GetDayOk returns a tuple with the Day field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) GetDayOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Day, true
}

// SetDay sets field value
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) SetDay(v time.Time) {
	o.Day = v
}

// GetIncome returns the Income field value
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) GetIncome() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Income
}

// GetIncomeOk returns a tuple with the Income field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) GetIncomeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Income, true
}

// SetIncome sets field value
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) SetIncome(v float64) {
	o.Income = v
}

// GetOutgo returns the Outgo field value
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) GetOutgo() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Outgo
}

// GetOutgoOk returns a tuple with the Outgo field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) GetOutgoOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outgo, true
}

// SetOutgo sets field value
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) SetOutgo(v float64) {
	o.Outgo = v
}

// GetBilance returns the Bilance field value
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) GetBilance() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Bilance
}

// GetBilanceOk returns a tuple with the Bilance field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) GetBilanceOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bilance, true
}

// SetBilance sets field value
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) SetBilance(v float64) {
	o.Bilance = v
}

// GetCurrency returns the Currency field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) GetCurrency() string {
	if o == nil || o.Currency.Get() == nil {
		var ret string
		return ret
	}

	return *o.Currency.Get()
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Currency.Get(), o.Currency.IsSet()
}

// SetCurrency sets field value
func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) SetCurrency(v string) {
	o.Currency.Set(&v)
}

func (o FPHSpedVAPIObjectsMoneyMoneyTransferDay) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FPHSpedVAPIObjectsMoneyMoneyTransferDay) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["day"] = o.Day
	toSerialize["income"] = o.Income
	toSerialize["outgo"] = o.Outgo
	toSerialize["bilance"] = o.Bilance
	toSerialize["currency"] = o.Currency.Get()
	return toSerialize, nil
}

func (o *FPHSpedVAPIObjectsMoneyMoneyTransferDay) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"day",
		"income",
		"outgo",
		"bilance",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFPHSpedVAPIObjectsMoneyMoneyTransferDay := _FPHSpedVAPIObjectsMoneyMoneyTransferDay{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFPHSpedVAPIObjectsMoneyMoneyTransferDay)

	if err != nil {
		return err
	}

	*o = FPHSpedVAPIObjectsMoneyMoneyTransferDay(varFPHSpedVAPIObjectsMoneyMoneyTransferDay)

	return err
}

type NullableFPHSpedVAPIObjectsMoneyMoneyTransferDay struct {
	value *FPHSpedVAPIObjectsMoneyMoneyTransferDay
	isSet bool
}

func (v NullableFPHSpedVAPIObjectsMoneyMoneyTransferDay) Get() *FPHSpedVAPIObjectsMoneyMoneyTransferDay {
	return v.value
}

func (v *NullableFPHSpedVAPIObjectsMoneyMoneyTransferDay) Set(val *FPHSpedVAPIObjectsMoneyMoneyTransferDay) {
	v.value = val
	v.isSet = true
}

func (v NullableFPHSpedVAPIObjectsMoneyMoneyTransferDay) IsSet() bool {
	return v.isSet
}

func (v *NullableFPHSpedVAPIObjectsMoneyMoneyTransferDay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFPHSpedVAPIObjectsMoneyMoneyTransferDay(val *FPHSpedVAPIObjectsMoneyMoneyTransferDay) *NullableFPHSpedVAPIObjectsMoneyMoneyTransferDay {
	return &NullableFPHSpedVAPIObjectsMoneyMoneyTransferDay{value: val, isSet: true}
}

func (v NullableFPHSpedVAPIObjectsMoneyMoneyTransferDay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFPHSpedVAPIObjectsMoneyMoneyTransferDay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


