/*
SpedV API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FPHSpedVAPIObjectsSpeditionsLiteRank type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FPHSpedVAPIObjectsSpeditionsLiteRank{}

// FPHSpedVAPIObjectsSpeditionsLiteRank struct for FPHSpedVAPIObjectsSpeditionsLiteRank
type FPHSpedVAPIObjectsSpeditionsLiteRank struct {
	Id int32 `json:"id"`
	Name NullableString `json:"name"`
	Color NullableString `json:"color"`
}

type _FPHSpedVAPIObjectsSpeditionsLiteRank FPHSpedVAPIObjectsSpeditionsLiteRank

// NewFPHSpedVAPIObjectsSpeditionsLiteRank instantiates a new FPHSpedVAPIObjectsSpeditionsLiteRank object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFPHSpedVAPIObjectsSpeditionsLiteRank(id int32, name NullableString, color NullableString) *FPHSpedVAPIObjectsSpeditionsLiteRank {
	this := FPHSpedVAPIObjectsSpeditionsLiteRank{}
	this.Id = id
	this.Name = name
	this.Color = color
	return &this
}

// NewFPHSpedVAPIObjectsSpeditionsLiteRankWithDefaults instantiates a new FPHSpedVAPIObjectsSpeditionsLiteRank object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFPHSpedVAPIObjectsSpeditionsLiteRankWithDefaults() *FPHSpedVAPIObjectsSpeditionsLiteRank {
	this := FPHSpedVAPIObjectsSpeditionsLiteRank{}
	return &this
}

// GetId returns the Id field value
func (o *FPHSpedVAPIObjectsSpeditionsLiteRank) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsLiteRank) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FPHSpedVAPIObjectsSpeditionsLiteRank) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSpeditionsLiteRank) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsLiteRank) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *FPHSpedVAPIObjectsSpeditionsLiteRank) SetName(v string) {
	o.Name.Set(&v)
}

// GetColor returns the Color field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSpeditionsLiteRank) GetColor() string {
	if o == nil || o.Color.Get() == nil {
		var ret string
		return ret
	}

	return *o.Color.Get()
}

// GetColorOk returns a tuple with the Color field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsLiteRank) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Color.Get(), o.Color.IsSet()
}

// SetColor sets field value
func (o *FPHSpedVAPIObjectsSpeditionsLiteRank) SetColor(v string) {
	o.Color.Set(&v)
}

func (o FPHSpedVAPIObjectsSpeditionsLiteRank) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FPHSpedVAPIObjectsSpeditionsLiteRank) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name.Get()
	toSerialize["color"] = o.Color.Get()
	return toSerialize, nil
}

func (o *FPHSpedVAPIObjectsSpeditionsLiteRank) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"color",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFPHSpedVAPIObjectsSpeditionsLiteRank := _FPHSpedVAPIObjectsSpeditionsLiteRank{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFPHSpedVAPIObjectsSpeditionsLiteRank)

	if err != nil {
		return err
	}

	*o = FPHSpedVAPIObjectsSpeditionsLiteRank(varFPHSpedVAPIObjectsSpeditionsLiteRank)

	return err
}

type NullableFPHSpedVAPIObjectsSpeditionsLiteRank struct {
	value *FPHSpedVAPIObjectsSpeditionsLiteRank
	isSet bool
}

func (v NullableFPHSpedVAPIObjectsSpeditionsLiteRank) Get() *FPHSpedVAPIObjectsSpeditionsLiteRank {
	return v.value
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsLiteRank) Set(val *FPHSpedVAPIObjectsSpeditionsLiteRank) {
	v.value = val
	v.isSet = true
}

func (v NullableFPHSpedVAPIObjectsSpeditionsLiteRank) IsSet() bool {
	return v.isSet
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsLiteRank) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFPHSpedVAPIObjectsSpeditionsLiteRank(val *FPHSpedVAPIObjectsSpeditionsLiteRank) *NullableFPHSpedVAPIObjectsSpeditionsLiteRank {
	return &NullableFPHSpedVAPIObjectsSpeditionsLiteRank{value: val, isSet: true}
}

func (v NullableFPHSpedVAPIObjectsSpeditionsLiteRank) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsLiteRank) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


