/*
SpedV API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FPHSpedVAPIObjectsLiveSystemStatistic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FPHSpedVAPIObjectsLiveSystemStatistic{}

// FPHSpedVAPIObjectsLiveSystemStatistic struct for FPHSpedVAPIObjectsLiveSystemStatistic
type FPHSpedVAPIObjectsLiveSystemStatistic struct {
	LastRestart time.Time `json:"lastRestart"`
	Lastrefresh time.Time `json:"lastrefresh"`
	Loadcitys []FPHSpedVAPIObjectsLiveSystemStatisticEntry `json:"loadcitys"`
	Destcitys []FPHSpedVAPIObjectsLiveSystemStatisticEntry `json:"destcitys"`
	Freights []FPHSpedVAPIObjectsLiveSystemStatisticEntry `json:"freights"`
	Usedmaps []FPHSpedVAPIObjectsLiveSystemStatisticEntry `json:"usedmaps"`
	WeeklyStatsEUR []FPHSpedVAPIObjectsLiveSystemStatisticEntry `json:"weeklyStatsEUR"`
	WeeklyStatsKontorEUR []FPHSpedVAPIObjectsLiveSystemStatisticEntry `json:"weeklyStatsKontorEUR"`
	WeeklyStatsExternalEUR []FPHSpedVAPIObjectsLiveSystemStatisticEntry `json:"weeklyStatsExternalEUR"`
	WeeklyStatsKM []FPHSpedVAPIObjectsLiveSystemStatisticEntry `json:"weeklyStatsKM"`
	Places FPHSpedVAPIObjectsLiveMyPlaceStructure `json:"places"`
	OnlineUser int32 `json:"onlineUser"`
	ActiveSpedLastMonth int32 `json:"activeSpedLastMonth"`
	ActiveUserLastMonth int32 `json:"activeUserLastMonth"`
	NextTaskID int32 `json:"nextTaskID"`
	ActRAM int64 `json:"actRAM"`
	FormatActRAM NullableString `json:"formatActRAM"`
	TaskLastDay int32 `json:"taskLastDay"`
	ExchangeRate float64 `json:"exchangeRate"`
}

type _FPHSpedVAPIObjectsLiveSystemStatistic FPHSpedVAPIObjectsLiveSystemStatistic

// NewFPHSpedVAPIObjectsLiveSystemStatistic instantiates a new FPHSpedVAPIObjectsLiveSystemStatistic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFPHSpedVAPIObjectsLiveSystemStatistic(lastRestart time.Time, lastrefresh time.Time, loadcitys []FPHSpedVAPIObjectsLiveSystemStatisticEntry, destcitys []FPHSpedVAPIObjectsLiveSystemStatisticEntry, freights []FPHSpedVAPIObjectsLiveSystemStatisticEntry, usedmaps []FPHSpedVAPIObjectsLiveSystemStatisticEntry, weeklyStatsEUR []FPHSpedVAPIObjectsLiveSystemStatisticEntry, weeklyStatsKontorEUR []FPHSpedVAPIObjectsLiveSystemStatisticEntry, weeklyStatsExternalEUR []FPHSpedVAPIObjectsLiveSystemStatisticEntry, weeklyStatsKM []FPHSpedVAPIObjectsLiveSystemStatisticEntry, places FPHSpedVAPIObjectsLiveMyPlaceStructure, onlineUser int32, activeSpedLastMonth int32, activeUserLastMonth int32, nextTaskID int32, actRAM int64, formatActRAM NullableString, taskLastDay int32, exchangeRate float64) *FPHSpedVAPIObjectsLiveSystemStatistic {
	this := FPHSpedVAPIObjectsLiveSystemStatistic{}
	this.LastRestart = lastRestart
	this.Lastrefresh = lastrefresh
	this.Loadcitys = loadcitys
	this.Destcitys = destcitys
	this.Freights = freights
	this.Usedmaps = usedmaps
	this.WeeklyStatsEUR = weeklyStatsEUR
	this.WeeklyStatsKontorEUR = weeklyStatsKontorEUR
	this.WeeklyStatsExternalEUR = weeklyStatsExternalEUR
	this.WeeklyStatsKM = weeklyStatsKM
	this.Places = places
	this.OnlineUser = onlineUser
	this.ActiveSpedLastMonth = activeSpedLastMonth
	this.ActiveUserLastMonth = activeUserLastMonth
	this.NextTaskID = nextTaskID
	this.ActRAM = actRAM
	this.FormatActRAM = formatActRAM
	this.TaskLastDay = taskLastDay
	this.ExchangeRate = exchangeRate
	return &this
}

// NewFPHSpedVAPIObjectsLiveSystemStatisticWithDefaults instantiates a new FPHSpedVAPIObjectsLiveSystemStatistic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFPHSpedVAPIObjectsLiveSystemStatisticWithDefaults() *FPHSpedVAPIObjectsLiveSystemStatistic {
	this := FPHSpedVAPIObjectsLiveSystemStatistic{}
	return &this
}

// GetLastRestart returns the LastRestart field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetLastRestart() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastRestart
}

// GetLastRestartOk returns a tuple with the LastRestart field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetLastRestartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastRestart, true
}

// SetLastRestart sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetLastRestart(v time.Time) {
	o.LastRestart = v
}

// GetLastrefresh returns the Lastrefresh field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetLastrefresh() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Lastrefresh
}

// GetLastrefreshOk returns a tuple with the Lastrefresh field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetLastrefreshOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lastrefresh, true
}

// SetLastrefresh sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetLastrefresh(v time.Time) {
	o.Lastrefresh = v
}

// GetLoadcitys returns the Loadcitys field value
// If the value is explicit nil, the zero value for []FPHSpedVAPIObjectsLiveSystemStatisticEntry will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetLoadcitys() []FPHSpedVAPIObjectsLiveSystemStatisticEntry {
	if o == nil {
		var ret []FPHSpedVAPIObjectsLiveSystemStatisticEntry
		return ret
	}

	return o.Loadcitys
}

// GetLoadcitysOk returns a tuple with the Loadcitys field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetLoadcitysOk() ([]FPHSpedVAPIObjectsLiveSystemStatisticEntry, bool) {
	if o == nil || IsNil(o.Loadcitys) {
		return nil, false
	}
	return o.Loadcitys, true
}

// SetLoadcitys sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetLoadcitys(v []FPHSpedVAPIObjectsLiveSystemStatisticEntry) {
	o.Loadcitys = v
}

// GetDestcitys returns the Destcitys field value
// If the value is explicit nil, the zero value for []FPHSpedVAPIObjectsLiveSystemStatisticEntry will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetDestcitys() []FPHSpedVAPIObjectsLiveSystemStatisticEntry {
	if o == nil {
		var ret []FPHSpedVAPIObjectsLiveSystemStatisticEntry
		return ret
	}

	return o.Destcitys
}

// GetDestcitysOk returns a tuple with the Destcitys field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetDestcitysOk() ([]FPHSpedVAPIObjectsLiveSystemStatisticEntry, bool) {
	if o == nil || IsNil(o.Destcitys) {
		return nil, false
	}
	return o.Destcitys, true
}

// SetDestcitys sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetDestcitys(v []FPHSpedVAPIObjectsLiveSystemStatisticEntry) {
	o.Destcitys = v
}

// GetFreights returns the Freights field value
// If the value is explicit nil, the zero value for []FPHSpedVAPIObjectsLiveSystemStatisticEntry will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetFreights() []FPHSpedVAPIObjectsLiveSystemStatisticEntry {
	if o == nil {
		var ret []FPHSpedVAPIObjectsLiveSystemStatisticEntry
		return ret
	}

	return o.Freights
}

// GetFreightsOk returns a tuple with the Freights field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetFreightsOk() ([]FPHSpedVAPIObjectsLiveSystemStatisticEntry, bool) {
	if o == nil || IsNil(o.Freights) {
		return nil, false
	}
	return o.Freights, true
}

// SetFreights sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetFreights(v []FPHSpedVAPIObjectsLiveSystemStatisticEntry) {
	o.Freights = v
}

// GetUsedmaps returns the Usedmaps field value
// If the value is explicit nil, the zero value for []FPHSpedVAPIObjectsLiveSystemStatisticEntry will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetUsedmaps() []FPHSpedVAPIObjectsLiveSystemStatisticEntry {
	if o == nil {
		var ret []FPHSpedVAPIObjectsLiveSystemStatisticEntry
		return ret
	}

	return o.Usedmaps
}

// GetUsedmapsOk returns a tuple with the Usedmaps field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetUsedmapsOk() ([]FPHSpedVAPIObjectsLiveSystemStatisticEntry, bool) {
	if o == nil || IsNil(o.Usedmaps) {
		return nil, false
	}
	return o.Usedmaps, true
}

// SetUsedmaps sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetUsedmaps(v []FPHSpedVAPIObjectsLiveSystemStatisticEntry) {
	o.Usedmaps = v
}

// GetWeeklyStatsEUR returns the WeeklyStatsEUR field value
// If the value is explicit nil, the zero value for []FPHSpedVAPIObjectsLiveSystemStatisticEntry will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetWeeklyStatsEUR() []FPHSpedVAPIObjectsLiveSystemStatisticEntry {
	if o == nil {
		var ret []FPHSpedVAPIObjectsLiveSystemStatisticEntry
		return ret
	}

	return o.WeeklyStatsEUR
}

// GetWeeklyStatsEUROk returns a tuple with the WeeklyStatsEUR field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetWeeklyStatsEUROk() ([]FPHSpedVAPIObjectsLiveSystemStatisticEntry, bool) {
	if o == nil || IsNil(o.WeeklyStatsEUR) {
		return nil, false
	}
	return o.WeeklyStatsEUR, true
}

// SetWeeklyStatsEUR sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetWeeklyStatsEUR(v []FPHSpedVAPIObjectsLiveSystemStatisticEntry) {
	o.WeeklyStatsEUR = v
}

// GetWeeklyStatsKontorEUR returns the WeeklyStatsKontorEUR field value
// If the value is explicit nil, the zero value for []FPHSpedVAPIObjectsLiveSystemStatisticEntry will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetWeeklyStatsKontorEUR() []FPHSpedVAPIObjectsLiveSystemStatisticEntry {
	if o == nil {
		var ret []FPHSpedVAPIObjectsLiveSystemStatisticEntry
		return ret
	}

	return o.WeeklyStatsKontorEUR
}

// GetWeeklyStatsKontorEUROk returns a tuple with the WeeklyStatsKontorEUR field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetWeeklyStatsKontorEUROk() ([]FPHSpedVAPIObjectsLiveSystemStatisticEntry, bool) {
	if o == nil || IsNil(o.WeeklyStatsKontorEUR) {
		return nil, false
	}
	return o.WeeklyStatsKontorEUR, true
}

// SetWeeklyStatsKontorEUR sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetWeeklyStatsKontorEUR(v []FPHSpedVAPIObjectsLiveSystemStatisticEntry) {
	o.WeeklyStatsKontorEUR = v
}

// GetWeeklyStatsExternalEUR returns the WeeklyStatsExternalEUR field value
// If the value is explicit nil, the zero value for []FPHSpedVAPIObjectsLiveSystemStatisticEntry will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetWeeklyStatsExternalEUR() []FPHSpedVAPIObjectsLiveSystemStatisticEntry {
	if o == nil {
		var ret []FPHSpedVAPIObjectsLiveSystemStatisticEntry
		return ret
	}

	return o.WeeklyStatsExternalEUR
}

// GetWeeklyStatsExternalEUROk returns a tuple with the WeeklyStatsExternalEUR field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetWeeklyStatsExternalEUROk() ([]FPHSpedVAPIObjectsLiveSystemStatisticEntry, bool) {
	if o == nil || IsNil(o.WeeklyStatsExternalEUR) {
		return nil, false
	}
	return o.WeeklyStatsExternalEUR, true
}

// SetWeeklyStatsExternalEUR sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetWeeklyStatsExternalEUR(v []FPHSpedVAPIObjectsLiveSystemStatisticEntry) {
	o.WeeklyStatsExternalEUR = v
}

// GetWeeklyStatsKM returns the WeeklyStatsKM field value
// If the value is explicit nil, the zero value for []FPHSpedVAPIObjectsLiveSystemStatisticEntry will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetWeeklyStatsKM() []FPHSpedVAPIObjectsLiveSystemStatisticEntry {
	if o == nil {
		var ret []FPHSpedVAPIObjectsLiveSystemStatisticEntry
		return ret
	}

	return o.WeeklyStatsKM
}

// GetWeeklyStatsKMOk returns a tuple with the WeeklyStatsKM field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetWeeklyStatsKMOk() ([]FPHSpedVAPIObjectsLiveSystemStatisticEntry, bool) {
	if o == nil || IsNil(o.WeeklyStatsKM) {
		return nil, false
	}
	return o.WeeklyStatsKM, true
}

// SetWeeklyStatsKM sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetWeeklyStatsKM(v []FPHSpedVAPIObjectsLiveSystemStatisticEntry) {
	o.WeeklyStatsKM = v
}

// GetPlaces returns the Places field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetPlaces() FPHSpedVAPIObjectsLiveMyPlaceStructure {
	if o == nil {
		var ret FPHSpedVAPIObjectsLiveMyPlaceStructure
		return ret
	}

	return o.Places
}

// GetPlacesOk returns a tuple with the Places field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetPlacesOk() (*FPHSpedVAPIObjectsLiveMyPlaceStructure, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Places, true
}

// SetPlaces sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetPlaces(v FPHSpedVAPIObjectsLiveMyPlaceStructure) {
	o.Places = v
}

// GetOnlineUser returns the OnlineUser field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetOnlineUser() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OnlineUser
}

// GetOnlineUserOk returns a tuple with the OnlineUser field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetOnlineUserOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OnlineUser, true
}

// SetOnlineUser sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetOnlineUser(v int32) {
	o.OnlineUser = v
}

// GetActiveSpedLastMonth returns the ActiveSpedLastMonth field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetActiveSpedLastMonth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActiveSpedLastMonth
}

// GetActiveSpedLastMonthOk returns a tuple with the ActiveSpedLastMonth field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetActiveSpedLastMonthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveSpedLastMonth, true
}

// SetActiveSpedLastMonth sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetActiveSpedLastMonth(v int32) {
	o.ActiveSpedLastMonth = v
}

// GetActiveUserLastMonth returns the ActiveUserLastMonth field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetActiveUserLastMonth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActiveUserLastMonth
}

// GetActiveUserLastMonthOk returns a tuple with the ActiveUserLastMonth field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetActiveUserLastMonthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveUserLastMonth, true
}

// SetActiveUserLastMonth sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetActiveUserLastMonth(v int32) {
	o.ActiveUserLastMonth = v
}

// GetNextTaskID returns the NextTaskID field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetNextTaskID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NextTaskID
}

// GetNextTaskIDOk returns a tuple with the NextTaskID field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetNextTaskIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextTaskID, true
}

// SetNextTaskID sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetNextTaskID(v int32) {
	o.NextTaskID = v
}

// GetActRAM returns the ActRAM field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetActRAM() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ActRAM
}

// GetActRAMOk returns a tuple with the ActRAM field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetActRAMOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActRAM, true
}

// SetActRAM sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetActRAM(v int64) {
	o.ActRAM = v
}

// GetFormatActRAM returns the FormatActRAM field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetFormatActRAM() string {
	if o == nil || o.FormatActRAM.Get() == nil {
		var ret string
		return ret
	}

	return *o.FormatActRAM.Get()
}

// GetFormatActRAMOk returns a tuple with the FormatActRAM field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetFormatActRAMOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FormatActRAM.Get(), o.FormatActRAM.IsSet()
}

// SetFormatActRAM sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetFormatActRAM(v string) {
	o.FormatActRAM.Set(&v)
}

// GetTaskLastDay returns the TaskLastDay field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetTaskLastDay() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TaskLastDay
}

// GetTaskLastDayOk returns a tuple with the TaskLastDay field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetTaskLastDayOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskLastDay, true
}

// SetTaskLastDay sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetTaskLastDay(v int32) {
	o.TaskLastDay = v
}

// GetExchangeRate returns the ExchangeRate field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetExchangeRate() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.ExchangeRate
}

// GetExchangeRateOk returns a tuple with the ExchangeRate field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) GetExchangeRateOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExchangeRate, true
}

// SetExchangeRate sets field value
func (o *FPHSpedVAPIObjectsLiveSystemStatistic) SetExchangeRate(v float64) {
	o.ExchangeRate = v
}

func (o FPHSpedVAPIObjectsLiveSystemStatistic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FPHSpedVAPIObjectsLiveSystemStatistic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lastRestart"] = o.LastRestart
	toSerialize["lastrefresh"] = o.Lastrefresh
	if o.Loadcitys != nil {
		toSerialize["loadcitys"] = o.Loadcitys
	}
	if o.Destcitys != nil {
		toSerialize["destcitys"] = o.Destcitys
	}
	if o.Freights != nil {
		toSerialize["freights"] = o.Freights
	}
	if o.Usedmaps != nil {
		toSerialize["usedmaps"] = o.Usedmaps
	}
	if o.WeeklyStatsEUR != nil {
		toSerialize["weeklyStatsEUR"] = o.WeeklyStatsEUR
	}
	if o.WeeklyStatsKontorEUR != nil {
		toSerialize["weeklyStatsKontorEUR"] = o.WeeklyStatsKontorEUR
	}
	if o.WeeklyStatsExternalEUR != nil {
		toSerialize["weeklyStatsExternalEUR"] = o.WeeklyStatsExternalEUR
	}
	if o.WeeklyStatsKM != nil {
		toSerialize["weeklyStatsKM"] = o.WeeklyStatsKM
	}
	toSerialize["places"] = o.Places
	toSerialize["onlineUser"] = o.OnlineUser
	toSerialize["activeSpedLastMonth"] = o.ActiveSpedLastMonth
	toSerialize["activeUserLastMonth"] = o.ActiveUserLastMonth
	toSerialize["nextTaskID"] = o.NextTaskID
	toSerialize["actRAM"] = o.ActRAM
	toSerialize["formatActRAM"] = o.FormatActRAM.Get()
	toSerialize["taskLastDay"] = o.TaskLastDay
	toSerialize["exchangeRate"] = o.ExchangeRate
	return toSerialize, nil
}

func (o *FPHSpedVAPIObjectsLiveSystemStatistic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lastRestart",
		"lastrefresh",
		"loadcitys",
		"destcitys",
		"freights",
		"usedmaps",
		"weeklyStatsEUR",
		"weeklyStatsKontorEUR",
		"weeklyStatsExternalEUR",
		"weeklyStatsKM",
		"places",
		"onlineUser",
		"activeSpedLastMonth",
		"activeUserLastMonth",
		"nextTaskID",
		"actRAM",
		"formatActRAM",
		"taskLastDay",
		"exchangeRate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFPHSpedVAPIObjectsLiveSystemStatistic := _FPHSpedVAPIObjectsLiveSystemStatistic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFPHSpedVAPIObjectsLiveSystemStatistic)

	if err != nil {
		return err
	}

	*o = FPHSpedVAPIObjectsLiveSystemStatistic(varFPHSpedVAPIObjectsLiveSystemStatistic)

	return err
}

type NullableFPHSpedVAPIObjectsLiveSystemStatistic struct {
	value *FPHSpedVAPIObjectsLiveSystemStatistic
	isSet bool
}

func (v NullableFPHSpedVAPIObjectsLiveSystemStatistic) Get() *FPHSpedVAPIObjectsLiveSystemStatistic {
	return v.value
}

func (v *NullableFPHSpedVAPIObjectsLiveSystemStatistic) Set(val *FPHSpedVAPIObjectsLiveSystemStatistic) {
	v.value = val
	v.isSet = true
}

func (v NullableFPHSpedVAPIObjectsLiveSystemStatistic) IsSet() bool {
	return v.isSet
}

func (v *NullableFPHSpedVAPIObjectsLiveSystemStatistic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFPHSpedVAPIObjectsLiveSystemStatistic(val *FPHSpedVAPIObjectsLiveSystemStatistic) *NullableFPHSpedVAPIObjectsLiveSystemStatistic {
	return &NullableFPHSpedVAPIObjectsLiveSystemStatistic{value: val, isSet: true}
}

func (v NullableFPHSpedVAPIObjectsLiveSystemStatistic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFPHSpedVAPIObjectsLiveSystemStatistic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


