/*
SpedV API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry{}

// FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry struct for FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry
type FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry struct {
	Station NullableFPHSpedVAPIObjectsSimRailSimRailStation `json:"station"`
	ScheduledArrival string `json:"scheduledArrival"`
	ScheduledDeparture string `json:"scheduledDeparture"`
	Platform NullableString `json:"platform"`
	Track NullableInt32 `json:"track"`
	StopType NullableString `json:"stopType"`
	Line int32 `json:"line"`
	Km float64 `json:"km"`
	MaxSpeed int32 `json:"maxSpeed"`
	RealArrival NullableString `json:"realArrival"`
	RealDeparture NullableString `json:"realDeparture"`
}

type _FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry

// NewFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry instantiates a new FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry(station NullableFPHSpedVAPIObjectsSimRailSimRailStation, scheduledArrival string, scheduledDeparture string, platform NullableString, track NullableInt32, stopType NullableString, line int32, km float64, maxSpeed int32, realArrival NullableString, realDeparture NullableString) *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry {
	this := FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry{}
	this.Station = station
	this.ScheduledArrival = scheduledArrival
	this.ScheduledDeparture = scheduledDeparture
	this.Platform = platform
	this.Track = track
	this.StopType = stopType
	this.Line = line
	this.Km = km
	this.MaxSpeed = maxSpeed
	this.RealArrival = realArrival
	this.RealDeparture = realDeparture
	return &this
}

// NewFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntryWithDefaults instantiates a new FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntryWithDefaults() *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry {
	this := FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry{}
	return &this
}

// GetStation returns the Station field value
// If the value is explicit nil, the zero value for FPHSpedVAPIObjectsSimRailSimRailStation will be returned
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetStation() FPHSpedVAPIObjectsSimRailSimRailStation {
	if o == nil || o.Station.Get() == nil {
		var ret FPHSpedVAPIObjectsSimRailSimRailStation
		return ret
	}

	return *o.Station.Get()
}

// GetStationOk returns a tuple with the Station field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetStationOk() (*FPHSpedVAPIObjectsSimRailSimRailStation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Station.Get(), o.Station.IsSet()
}

// SetStation sets field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) SetStation(v FPHSpedVAPIObjectsSimRailSimRailStation) {
	o.Station.Set(&v)
}

// GetScheduledArrival returns the ScheduledArrival field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetScheduledArrival() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScheduledArrival
}

// GetScheduledArrivalOk returns a tuple with the ScheduledArrival field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetScheduledArrivalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduledArrival, true
}

// SetScheduledArrival sets field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) SetScheduledArrival(v string) {
	o.ScheduledArrival = v
}

// GetScheduledDeparture returns the ScheduledDeparture field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetScheduledDeparture() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScheduledDeparture
}

// GetScheduledDepartureOk returns a tuple with the ScheduledDeparture field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetScheduledDepartureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduledDeparture, true
}

// SetScheduledDeparture sets field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) SetScheduledDeparture(v string) {
	o.ScheduledDeparture = v
}

// GetPlatform returns the Platform field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetPlatform() string {
	if o == nil || o.Platform.Get() == nil {
		var ret string
		return ret
	}

	return *o.Platform.Get()
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetPlatformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Platform.Get(), o.Platform.IsSet()
}

// SetPlatform sets field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) SetPlatform(v string) {
	o.Platform.Set(&v)
}

// GetTrack returns the Track field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetTrack() int32 {
	if o == nil || o.Track.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Track.Get()
}

// GetTrackOk returns a tuple with the Track field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetTrackOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Track.Get(), o.Track.IsSet()
}

// SetTrack sets field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) SetTrack(v int32) {
	o.Track.Set(&v)
}

// GetStopType returns the StopType field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetStopType() string {
	if o == nil || o.StopType.Get() == nil {
		var ret string
		return ret
	}

	return *o.StopType.Get()
}

// GetStopTypeOk returns a tuple with the StopType field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetStopTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StopType.Get(), o.StopType.IsSet()
}

// SetStopType sets field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) SetStopType(v string) {
	o.StopType.Set(&v)
}

// GetLine returns the Line field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetLine() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Line
}

// GetLineOk returns a tuple with the Line field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetLineOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Line, true
}

// SetLine sets field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) SetLine(v int32) {
	o.Line = v
}

// GetKm returns the Km field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetKm() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Km
}

// GetKmOk returns a tuple with the Km field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetKmOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Km, true
}

// SetKm sets field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) SetKm(v float64) {
	o.Km = v
}

// GetMaxSpeed returns the MaxSpeed field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetMaxSpeed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxSpeed
}

// GetMaxSpeedOk returns a tuple with the MaxSpeed field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetMaxSpeedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxSpeed, true
}

// SetMaxSpeed sets field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) SetMaxSpeed(v int32) {
	o.MaxSpeed = v
}

// GetRealArrival returns the RealArrival field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetRealArrival() string {
	if o == nil || o.RealArrival.Get() == nil {
		var ret string
		return ret
	}

	return *o.RealArrival.Get()
}

// GetRealArrivalOk returns a tuple with the RealArrival field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetRealArrivalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RealArrival.Get(), o.RealArrival.IsSet()
}

// SetRealArrival sets field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) SetRealArrival(v string) {
	o.RealArrival.Set(&v)
}

// GetRealDeparture returns the RealDeparture field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetRealDeparture() string {
	if o == nil || o.RealDeparture.Get() == nil {
		var ret string
		return ret
	}

	return *o.RealDeparture.Get()
}

// GetRealDepartureOk returns a tuple with the RealDeparture field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) GetRealDepartureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RealDeparture.Get(), o.RealDeparture.IsSet()
}

// SetRealDeparture sets field value
func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) SetRealDeparture(v string) {
	o.RealDeparture.Set(&v)
}

func (o FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["station"] = o.Station.Get()
	toSerialize["scheduledArrival"] = o.ScheduledArrival
	toSerialize["scheduledDeparture"] = o.ScheduledDeparture
	toSerialize["platform"] = o.Platform.Get()
	toSerialize["track"] = o.Track.Get()
	toSerialize["stopType"] = o.StopType.Get()
	toSerialize["line"] = o.Line
	toSerialize["km"] = o.Km
	toSerialize["maxSpeed"] = o.MaxSpeed
	toSerialize["realArrival"] = o.RealArrival.Get()
	toSerialize["realDeparture"] = o.RealDeparture.Get()
	return toSerialize, nil
}

func (o *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"station",
		"scheduledArrival",
		"scheduledDeparture",
		"platform",
		"track",
		"stopType",
		"line",
		"km",
		"maxSpeed",
		"realArrival",
		"realDeparture",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry := _FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry)

	if err != nil {
		return err
	}

	*o = FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry(varFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry)

	return err
}

type NullableFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry struct {
	value *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry
	isSet bool
}

func (v NullableFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) Get() *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry {
	return v.value
}

func (v *NullableFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) Set(val *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry(val *FPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) *NullableFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry {
	return &NullableFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry{value: val, isSet: true}
}

func (v NullableFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFPHSpedVAPIObjectsSimRailSimRailTrainLiveTimetableEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


