/*
SpedV API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FPHSpedVAPIObjectsSpeditionsBoniType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FPHSpedVAPIObjectsSpeditionsBoniType{}

// FPHSpedVAPIObjectsSpeditionsBoniType struct for FPHSpedVAPIObjectsSpeditionsBoniType
type FPHSpedVAPIObjectsSpeditionsBoniType struct {
	Id int32 `json:"id"`
	MinValue int32 `json:"minValue"`
	MaxValue int32 `json:"maxValue"`
	//   0 = Value  1 = KM  -1 = NotSet
	Type FPHSpedVAPIEnumsBoniTypeType `json:"type"`
	OnlyKontor bool `json:"onlyKontor"`
	OnlyWithoutDamage bool `json:"onlyWithoutDamage"`
	OnlyWithoutSpeeding bool `json:"onlyWithoutSpeeding"`
	Value int32 `json:"value"`
}

type _FPHSpedVAPIObjectsSpeditionsBoniType FPHSpedVAPIObjectsSpeditionsBoniType

// NewFPHSpedVAPIObjectsSpeditionsBoniType instantiates a new FPHSpedVAPIObjectsSpeditionsBoniType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFPHSpedVAPIObjectsSpeditionsBoniType(id int32, minValue int32, maxValue int32, type_ FPHSpedVAPIEnumsBoniTypeType, onlyKontor bool, onlyWithoutDamage bool, onlyWithoutSpeeding bool, value int32) *FPHSpedVAPIObjectsSpeditionsBoniType {
	this := FPHSpedVAPIObjectsSpeditionsBoniType{}
	this.Id = id
	this.MinValue = minValue
	this.MaxValue = maxValue
	this.Type = type_
	this.OnlyKontor = onlyKontor
	this.OnlyWithoutDamage = onlyWithoutDamage
	this.OnlyWithoutSpeeding = onlyWithoutSpeeding
	this.Value = value
	return &this
}

// NewFPHSpedVAPIObjectsSpeditionsBoniTypeWithDefaults instantiates a new FPHSpedVAPIObjectsSpeditionsBoniType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFPHSpedVAPIObjectsSpeditionsBoniTypeWithDefaults() *FPHSpedVAPIObjectsSpeditionsBoniType {
	this := FPHSpedVAPIObjectsSpeditionsBoniType{}
	return &this
}

// GetId returns the Id field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) SetId(v int32) {
	o.Id = v
}

// GetMinValue returns the MinValue field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetMinValue() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MinValue
}

// GetMinValueOk returns a tuple with the MinValue field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetMinValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinValue, true
}

// SetMinValue sets field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) SetMinValue(v int32) {
	o.MinValue = v
}

// GetMaxValue returns the MaxValue field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetMaxValue() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxValue
}

// GetMaxValueOk returns a tuple with the MaxValue field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetMaxValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxValue, true
}

// SetMaxValue sets field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) SetMaxValue(v int32) {
	o.MaxValue = v
}

// GetType returns the Type field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetType() FPHSpedVAPIEnumsBoniTypeType {
	if o == nil {
		var ret FPHSpedVAPIEnumsBoniTypeType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetTypeOk() (*FPHSpedVAPIEnumsBoniTypeType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) SetType(v FPHSpedVAPIEnumsBoniTypeType) {
	o.Type = v
}

// GetOnlyKontor returns the OnlyKontor field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetOnlyKontor() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OnlyKontor
}

// GetOnlyKontorOk returns a tuple with the OnlyKontor field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetOnlyKontorOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OnlyKontor, true
}

// SetOnlyKontor sets field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) SetOnlyKontor(v bool) {
	o.OnlyKontor = v
}

// GetOnlyWithoutDamage returns the OnlyWithoutDamage field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetOnlyWithoutDamage() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OnlyWithoutDamage
}

// GetOnlyWithoutDamageOk returns a tuple with the OnlyWithoutDamage field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetOnlyWithoutDamageOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OnlyWithoutDamage, true
}

// SetOnlyWithoutDamage sets field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) SetOnlyWithoutDamage(v bool) {
	o.OnlyWithoutDamage = v
}

// GetOnlyWithoutSpeeding returns the OnlyWithoutSpeeding field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetOnlyWithoutSpeeding() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OnlyWithoutSpeeding
}

// GetOnlyWithoutSpeedingOk returns a tuple with the OnlyWithoutSpeeding field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetOnlyWithoutSpeedingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OnlyWithoutSpeeding, true
}

// SetOnlyWithoutSpeeding sets field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) SetOnlyWithoutSpeeding(v bool) {
	o.OnlyWithoutSpeeding = v
}

// GetValue returns the Value field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetValue() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) GetValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *FPHSpedVAPIObjectsSpeditionsBoniType) SetValue(v int32) {
	o.Value = v
}

func (o FPHSpedVAPIObjectsSpeditionsBoniType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FPHSpedVAPIObjectsSpeditionsBoniType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["minValue"] = o.MinValue
	toSerialize["maxValue"] = o.MaxValue
	toSerialize["type"] = o.Type
	toSerialize["onlyKontor"] = o.OnlyKontor
	toSerialize["onlyWithoutDamage"] = o.OnlyWithoutDamage
	toSerialize["onlyWithoutSpeeding"] = o.OnlyWithoutSpeeding
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *FPHSpedVAPIObjectsSpeditionsBoniType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"minValue",
		"maxValue",
		"type",
		"onlyKontor",
		"onlyWithoutDamage",
		"onlyWithoutSpeeding",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFPHSpedVAPIObjectsSpeditionsBoniType := _FPHSpedVAPIObjectsSpeditionsBoniType{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFPHSpedVAPIObjectsSpeditionsBoniType)

	if err != nil {
		return err
	}

	*o = FPHSpedVAPIObjectsSpeditionsBoniType(varFPHSpedVAPIObjectsSpeditionsBoniType)

	return err
}

type NullableFPHSpedVAPIObjectsSpeditionsBoniType struct {
	value *FPHSpedVAPIObjectsSpeditionsBoniType
	isSet bool
}

func (v NullableFPHSpedVAPIObjectsSpeditionsBoniType) Get() *FPHSpedVAPIObjectsSpeditionsBoniType {
	return v.value
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsBoniType) Set(val *FPHSpedVAPIObjectsSpeditionsBoniType) {
	v.value = val
	v.isSet = true
}

func (v NullableFPHSpedVAPIObjectsSpeditionsBoniType) IsSet() bool {
	return v.isSet
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsBoniType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFPHSpedVAPIObjectsSpeditionsBoniType(val *FPHSpedVAPIObjectsSpeditionsBoniType) *NullableFPHSpedVAPIObjectsSpeditionsBoniType {
	return &NullableFPHSpedVAPIObjectsSpeditionsBoniType{value: val, isSet: true}
}

func (v NullableFPHSpedVAPIObjectsSpeditionsBoniType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsBoniType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


