/*
SpedV API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FPHSpedVAPIObjectsUsersFullUserInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FPHSpedVAPIObjectsUsersFullUserInfo{}

// FPHSpedVAPIObjectsUsersFullUserInfo struct for FPHSpedVAPIObjectsUsersFullUserInfo
type FPHSpedVAPIObjectsUsersFullUserInfo struct {
	Id int32 `json:"id"`
	SteamID int64 `json:"steamID"`
	AuthCode NullableString `json:"authCode"`
	PlusUntil time.Time `json:"plusUntil"`
	PlusActive bool `json:"plusActive"`
	BannedTill time.Time `json:"bannedTill"`
	IsBanned bool `json:"isBanned"`
	BannedReason NullableString `json:"bannedReason"`
	EMail NullableString `json:"eMail"`
	RealName NullableString `json:"realName"`
	AboutMe NullableString `json:"aboutMe"`
	Birthday time.Time `json:"birthday"`
	SteamImgURL NullableString `json:"steamImgURL"`
	Residence NullableString `json:"residence"`
	UserName NullableString `json:"userName"`
	KontorActivated bool `json:"kontorActivated"`
	ChangelogVisible bool `json:"changelogVisible"`
	DeletionFrist int32 `json:"deletionFrist"`
	TfaActivated bool `json:"tfaActivated"`
	IsAlphaTester bool `json:"isAlphaTester"`
	IsTrustedUser bool `json:"isTrustedUser"`
	//   0 = None  1 = SeeLiveData  2 = HandleScreenshots  4 = HandleTaskCheck  8 = TicketSystem  16 = ViewData  32 = ChangeData  64 = BanUser  128 = MapImport  256 = KontorManagement  512 = IsManagement
	SystemAdminPermissions FPHSpedVAPIAdminPermissionEnum `json:"systemAdminPermissions"`
	SystemAdminRankName NullableString `json:"systemAdminRankName"`
	TwitchName NullableString `json:"twitchName"`
	TwitchID NullableInt32 `json:"twitchID"`
	DiscordUID NullableInt64 `json:"discordUID"`
	Spedition NullableFPHSpedVAPIObjectsSpeditionsSpedition `json:"spedition"`
	Rank NullableFPHSpedVAPIObjectsSpeditionsRank `json:"rank"`
	Achievements map[string]interface{} `json:"achievements"`
	InSped bool `json:"inSped"`
	FormatName NullableString `json:"formatName"`
	LastTaskTime time.Time `json:"lastTaskTime"`
	IsInCooldown bool `json:"isInCooldown"`
	MainBankAccount NullableFPHSpedVAPIObjectsMoneyLiteBankAccount `json:"mainBankAccount"`
	SpeditionJoinDate NullableTime `json:"speditionJoinDate"`
}

type _FPHSpedVAPIObjectsUsersFullUserInfo FPHSpedVAPIObjectsUsersFullUserInfo

// NewFPHSpedVAPIObjectsUsersFullUserInfo instantiates a new FPHSpedVAPIObjectsUsersFullUserInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFPHSpedVAPIObjectsUsersFullUserInfo(id int32, steamID int64, authCode NullableString, plusUntil time.Time, plusActive bool, bannedTill time.Time, isBanned bool, bannedReason NullableString, eMail NullableString, realName NullableString, aboutMe NullableString, birthday time.Time, steamImgURL NullableString, residence NullableString, userName NullableString, kontorActivated bool, changelogVisible bool, deletionFrist int32, tfaActivated bool, isAlphaTester bool, isTrustedUser bool, systemAdminPermissions FPHSpedVAPIAdminPermissionEnum, systemAdminRankName NullableString, twitchName NullableString, twitchID NullableInt32, discordUID NullableInt64, spedition NullableFPHSpedVAPIObjectsSpeditionsSpedition, rank NullableFPHSpedVAPIObjectsSpeditionsRank, achievements map[string]interface{}, inSped bool, formatName NullableString, lastTaskTime time.Time, isInCooldown bool, mainBankAccount NullableFPHSpedVAPIObjectsMoneyLiteBankAccount, speditionJoinDate NullableTime) *FPHSpedVAPIObjectsUsersFullUserInfo {
	this := FPHSpedVAPIObjectsUsersFullUserInfo{}
	this.Id = id
	this.SteamID = steamID
	this.AuthCode = authCode
	this.PlusUntil = plusUntil
	this.PlusActive = plusActive
	this.BannedTill = bannedTill
	this.IsBanned = isBanned
	this.BannedReason = bannedReason
	this.EMail = eMail
	this.RealName = realName
	this.AboutMe = aboutMe
	this.Birthday = birthday
	this.SteamImgURL = steamImgURL
	this.Residence = residence
	this.UserName = userName
	this.KontorActivated = kontorActivated
	this.ChangelogVisible = changelogVisible
	this.DeletionFrist = deletionFrist
	this.TfaActivated = tfaActivated
	this.IsAlphaTester = isAlphaTester
	this.IsTrustedUser = isTrustedUser
	this.SystemAdminPermissions = systemAdminPermissions
	this.SystemAdminRankName = systemAdminRankName
	this.TwitchName = twitchName
	this.TwitchID = twitchID
	this.DiscordUID = discordUID
	this.Spedition = spedition
	this.Rank = rank
	this.Achievements = achievements
	this.InSped = inSped
	this.FormatName = formatName
	this.LastTaskTime = lastTaskTime
	this.IsInCooldown = isInCooldown
	this.MainBankAccount = mainBankAccount
	this.SpeditionJoinDate = speditionJoinDate
	return &this
}

// NewFPHSpedVAPIObjectsUsersFullUserInfoWithDefaults instantiates a new FPHSpedVAPIObjectsUsersFullUserInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFPHSpedVAPIObjectsUsersFullUserInfoWithDefaults() *FPHSpedVAPIObjectsUsersFullUserInfo {
	this := FPHSpedVAPIObjectsUsersFullUserInfo{}
	return &this
}

// GetId returns the Id field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetId(v int32) {
	o.Id = v
}

// GetSteamID returns the SteamID field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetSteamID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SteamID
}

// GetSteamIDOk returns a tuple with the SteamID field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetSteamIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SteamID, true
}

// SetSteamID sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetSteamID(v int64) {
	o.SteamID = v
}

// GetAuthCode returns the AuthCode field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetAuthCode() string {
	if o == nil || o.AuthCode.Get() == nil {
		var ret string
		return ret
	}

	return *o.AuthCode.Get()
}

// GetAuthCodeOk returns a tuple with the AuthCode field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetAuthCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthCode.Get(), o.AuthCode.IsSet()
}

// SetAuthCode sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetAuthCode(v string) {
	o.AuthCode.Set(&v)
}

// GetPlusUntil returns the PlusUntil field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetPlusUntil() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.PlusUntil
}

// GetPlusUntilOk returns a tuple with the PlusUntil field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetPlusUntilOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlusUntil, true
}

// SetPlusUntil sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetPlusUntil(v time.Time) {
	o.PlusUntil = v
}

// GetPlusActive returns the PlusActive field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetPlusActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PlusActive
}

// GetPlusActiveOk returns a tuple with the PlusActive field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetPlusActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlusActive, true
}

// SetPlusActive sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetPlusActive(v bool) {
	o.PlusActive = v
}

// GetBannedTill returns the BannedTill field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetBannedTill() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.BannedTill
}

// GetBannedTillOk returns a tuple with the BannedTill field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetBannedTillOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BannedTill, true
}

// SetBannedTill sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetBannedTill(v time.Time) {
	o.BannedTill = v
}

// GetIsBanned returns the IsBanned field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetIsBanned() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsBanned
}

// GetIsBannedOk returns a tuple with the IsBanned field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetIsBannedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsBanned, true
}

// SetIsBanned sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetIsBanned(v bool) {
	o.IsBanned = v
}

// GetBannedReason returns the BannedReason field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetBannedReason() string {
	if o == nil || o.BannedReason.Get() == nil {
		var ret string
		return ret
	}

	return *o.BannedReason.Get()
}

// GetBannedReasonOk returns a tuple with the BannedReason field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetBannedReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BannedReason.Get(), o.BannedReason.IsSet()
}

// SetBannedReason sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetBannedReason(v string) {
	o.BannedReason.Set(&v)
}

// GetEMail returns the EMail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetEMail() string {
	if o == nil || o.EMail.Get() == nil {
		var ret string
		return ret
	}

	return *o.EMail.Get()
}

// GetEMailOk returns a tuple with the EMail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetEMailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EMail.Get(), o.EMail.IsSet()
}

// SetEMail sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetEMail(v string) {
	o.EMail.Set(&v)
}

// GetRealName returns the RealName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetRealName() string {
	if o == nil || o.RealName.Get() == nil {
		var ret string
		return ret
	}

	return *o.RealName.Get()
}

// GetRealNameOk returns a tuple with the RealName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetRealNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RealName.Get(), o.RealName.IsSet()
}

// SetRealName sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetRealName(v string) {
	o.RealName.Set(&v)
}

// GetAboutMe returns the AboutMe field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetAboutMe() string {
	if o == nil || o.AboutMe.Get() == nil {
		var ret string
		return ret
	}

	return *o.AboutMe.Get()
}

// GetAboutMeOk returns a tuple with the AboutMe field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetAboutMeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AboutMe.Get(), o.AboutMe.IsSet()
}

// SetAboutMe sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetAboutMe(v string) {
	o.AboutMe.Set(&v)
}

// GetBirthday returns the Birthday field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetBirthday() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Birthday
}

// GetBirthdayOk returns a tuple with the Birthday field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetBirthdayOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Birthday, true
}

// SetBirthday sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetBirthday(v time.Time) {
	o.Birthday = v
}

// GetSteamImgURL returns the SteamImgURL field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetSteamImgURL() string {
	if o == nil || o.SteamImgURL.Get() == nil {
		var ret string
		return ret
	}

	return *o.SteamImgURL.Get()
}

// GetSteamImgURLOk returns a tuple with the SteamImgURL field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetSteamImgURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SteamImgURL.Get(), o.SteamImgURL.IsSet()
}

// SetSteamImgURL sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetSteamImgURL(v string) {
	o.SteamImgURL.Set(&v)
}

// GetResidence returns the Residence field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetResidence() string {
	if o == nil || o.Residence.Get() == nil {
		var ret string
		return ret
	}

	return *o.Residence.Get()
}

// GetResidenceOk returns a tuple with the Residence field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetResidenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Residence.Get(), o.Residence.IsSet()
}

// SetResidence sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetResidence(v string) {
	o.Residence.Set(&v)
}

// GetUserName returns the UserName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetUserName() string {
	if o == nil || o.UserName.Get() == nil {
		var ret string
		return ret
	}

	return *o.UserName.Get()
}

// GetUserNameOk returns a tuple with the UserName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetUserNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserName.Get(), o.UserName.IsSet()
}

// SetUserName sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetUserName(v string) {
	o.UserName.Set(&v)
}

// GetKontorActivated returns the KontorActivated field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetKontorActivated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.KontorActivated
}

// GetKontorActivatedOk returns a tuple with the KontorActivated field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetKontorActivatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KontorActivated, true
}

// SetKontorActivated sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetKontorActivated(v bool) {
	o.KontorActivated = v
}

// GetChangelogVisible returns the ChangelogVisible field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetChangelogVisible() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ChangelogVisible
}

// GetChangelogVisibleOk returns a tuple with the ChangelogVisible field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetChangelogVisibleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangelogVisible, true
}

// SetChangelogVisible sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetChangelogVisible(v bool) {
	o.ChangelogVisible = v
}

// GetDeletionFrist returns the DeletionFrist field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetDeletionFrist() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DeletionFrist
}

// GetDeletionFristOk returns a tuple with the DeletionFrist field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetDeletionFristOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeletionFrist, true
}

// SetDeletionFrist sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetDeletionFrist(v int32) {
	o.DeletionFrist = v
}

// GetTfaActivated returns the TfaActivated field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetTfaActivated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TfaActivated
}

// GetTfaActivatedOk returns a tuple with the TfaActivated field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetTfaActivatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TfaActivated, true
}

// SetTfaActivated sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetTfaActivated(v bool) {
	o.TfaActivated = v
}

// GetIsAlphaTester returns the IsAlphaTester field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetIsAlphaTester() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsAlphaTester
}

// GetIsAlphaTesterOk returns a tuple with the IsAlphaTester field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetIsAlphaTesterOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsAlphaTester, true
}

// SetIsAlphaTester sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetIsAlphaTester(v bool) {
	o.IsAlphaTester = v
}

// GetIsTrustedUser returns the IsTrustedUser field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetIsTrustedUser() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsTrustedUser
}

// GetIsTrustedUserOk returns a tuple with the IsTrustedUser field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetIsTrustedUserOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsTrustedUser, true
}

// SetIsTrustedUser sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetIsTrustedUser(v bool) {
	o.IsTrustedUser = v
}

// GetSystemAdminPermissions returns the SystemAdminPermissions field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetSystemAdminPermissions() FPHSpedVAPIAdminPermissionEnum {
	if o == nil {
		var ret FPHSpedVAPIAdminPermissionEnum
		return ret
	}

	return o.SystemAdminPermissions
}

// GetSystemAdminPermissionsOk returns a tuple with the SystemAdminPermissions field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetSystemAdminPermissionsOk() (*FPHSpedVAPIAdminPermissionEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SystemAdminPermissions, true
}

// SetSystemAdminPermissions sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetSystemAdminPermissions(v FPHSpedVAPIAdminPermissionEnum) {
	o.SystemAdminPermissions = v
}

// GetSystemAdminRankName returns the SystemAdminRankName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetSystemAdminRankName() string {
	if o == nil || o.SystemAdminRankName.Get() == nil {
		var ret string
		return ret
	}

	return *o.SystemAdminRankName.Get()
}

// GetSystemAdminRankNameOk returns a tuple with the SystemAdminRankName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetSystemAdminRankNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SystemAdminRankName.Get(), o.SystemAdminRankName.IsSet()
}

// SetSystemAdminRankName sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetSystemAdminRankName(v string) {
	o.SystemAdminRankName.Set(&v)
}

// GetTwitchName returns the TwitchName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetTwitchName() string {
	if o == nil || o.TwitchName.Get() == nil {
		var ret string
		return ret
	}

	return *o.TwitchName.Get()
}

// GetTwitchNameOk returns a tuple with the TwitchName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetTwitchNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TwitchName.Get(), o.TwitchName.IsSet()
}

// SetTwitchName sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetTwitchName(v string) {
	o.TwitchName.Set(&v)
}

// GetTwitchID returns the TwitchID field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetTwitchID() int32 {
	if o == nil || o.TwitchID.Get() == nil {
		var ret int32
		return ret
	}

	return *o.TwitchID.Get()
}

// GetTwitchIDOk returns a tuple with the TwitchID field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetTwitchIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TwitchID.Get(), o.TwitchID.IsSet()
}

// SetTwitchID sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetTwitchID(v int32) {
	o.TwitchID.Set(&v)
}

// GetDiscordUID returns the DiscordUID field value
// If the value is explicit nil, the zero value for int64 will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetDiscordUID() int64 {
	if o == nil || o.DiscordUID.Get() == nil {
		var ret int64
		return ret
	}

	return *o.DiscordUID.Get()
}

// GetDiscordUIDOk returns a tuple with the DiscordUID field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetDiscordUIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.DiscordUID.Get(), o.DiscordUID.IsSet()
}

// SetDiscordUID sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetDiscordUID(v int64) {
	o.DiscordUID.Set(&v)
}

// GetSpedition returns the Spedition field value
// If the value is explicit nil, the zero value for FPHSpedVAPIObjectsSpeditionsSpedition will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetSpedition() FPHSpedVAPIObjectsSpeditionsSpedition {
	if o == nil || o.Spedition.Get() == nil {
		var ret FPHSpedVAPIObjectsSpeditionsSpedition
		return ret
	}

	return *o.Spedition.Get()
}

// GetSpeditionOk returns a tuple with the Spedition field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetSpeditionOk() (*FPHSpedVAPIObjectsSpeditionsSpedition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Spedition.Get(), o.Spedition.IsSet()
}

// SetSpedition sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetSpedition(v FPHSpedVAPIObjectsSpeditionsSpedition) {
	o.Spedition.Set(&v)
}

// GetRank returns the Rank field value
// If the value is explicit nil, the zero value for FPHSpedVAPIObjectsSpeditionsRank will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetRank() FPHSpedVAPIObjectsSpeditionsRank {
	if o == nil || o.Rank.Get() == nil {
		var ret FPHSpedVAPIObjectsSpeditionsRank
		return ret
	}

	return *o.Rank.Get()
}

// GetRankOk returns a tuple with the Rank field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetRankOk() (*FPHSpedVAPIObjectsSpeditionsRank, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rank.Get(), o.Rank.IsSet()
}

// SetRank sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetRank(v FPHSpedVAPIObjectsSpeditionsRank) {
	o.Rank.Set(&v)
}

// GetAchievements returns the Achievements field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetAchievements() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Achievements
}

// GetAchievementsOk returns a tuple with the Achievements field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetAchievementsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Achievements) {
		return map[string]interface{}{}, false
	}
	return o.Achievements, true
}

// SetAchievements sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetAchievements(v map[string]interface{}) {
	o.Achievements = v
}

// GetInSped returns the InSped field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetInSped() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.InSped
}

// GetInSpedOk returns a tuple with the InSped field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetInSpedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InSped, true
}

// SetInSped sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetInSped(v bool) {
	o.InSped = v
}

// GetFormatName returns the FormatName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetFormatName() string {
	if o == nil || o.FormatName.Get() == nil {
		var ret string
		return ret
	}

	return *o.FormatName.Get()
}

// GetFormatNameOk returns a tuple with the FormatName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetFormatNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FormatName.Get(), o.FormatName.IsSet()
}

// SetFormatName sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetFormatName(v string) {
	o.FormatName.Set(&v)
}

// GetLastTaskTime returns the LastTaskTime field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetLastTaskTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastTaskTime
}

// GetLastTaskTimeOk returns a tuple with the LastTaskTime field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetLastTaskTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastTaskTime, true
}

// SetLastTaskTime sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetLastTaskTime(v time.Time) {
	o.LastTaskTime = v
}

// GetIsInCooldown returns the IsInCooldown field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetIsInCooldown() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsInCooldown
}

// GetIsInCooldownOk returns a tuple with the IsInCooldown field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetIsInCooldownOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsInCooldown, true
}

// SetIsInCooldown sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetIsInCooldown(v bool) {
	o.IsInCooldown = v
}

// GetMainBankAccount returns the MainBankAccount field value
// If the value is explicit nil, the zero value for FPHSpedVAPIObjectsMoneyLiteBankAccount will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetMainBankAccount() FPHSpedVAPIObjectsMoneyLiteBankAccount {
	if o == nil || o.MainBankAccount.Get() == nil {
		var ret FPHSpedVAPIObjectsMoneyLiteBankAccount
		return ret
	}

	return *o.MainBankAccount.Get()
}

// GetMainBankAccountOk returns a tuple with the MainBankAccount field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetMainBankAccountOk() (*FPHSpedVAPIObjectsMoneyLiteBankAccount, bool) {
	if o == nil {
		return nil, false
	}
	return o.MainBankAccount.Get(), o.MainBankAccount.IsSet()
}

// SetMainBankAccount sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetMainBankAccount(v FPHSpedVAPIObjectsMoneyLiteBankAccount) {
	o.MainBankAccount.Set(&v)
}

// GetSpeditionJoinDate returns the SpeditionJoinDate field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetSpeditionJoinDate() time.Time {
	if o == nil || o.SpeditionJoinDate.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.SpeditionJoinDate.Get()
}

// GetSpeditionJoinDateOk returns a tuple with the SpeditionJoinDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) GetSpeditionJoinDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpeditionJoinDate.Get(), o.SpeditionJoinDate.IsSet()
}

// SetSpeditionJoinDate sets field value
func (o *FPHSpedVAPIObjectsUsersFullUserInfo) SetSpeditionJoinDate(v time.Time) {
	o.SpeditionJoinDate.Set(&v)
}

func (o FPHSpedVAPIObjectsUsersFullUserInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FPHSpedVAPIObjectsUsersFullUserInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["steamID"] = o.SteamID
	toSerialize["authCode"] = o.AuthCode.Get()
	toSerialize["plusUntil"] = o.PlusUntil
	toSerialize["plusActive"] = o.PlusActive
	toSerialize["bannedTill"] = o.BannedTill
	toSerialize["isBanned"] = o.IsBanned
	toSerialize["bannedReason"] = o.BannedReason.Get()
	toSerialize["eMail"] = o.EMail.Get()
	toSerialize["realName"] = o.RealName.Get()
	toSerialize["aboutMe"] = o.AboutMe.Get()
	toSerialize["birthday"] = o.Birthday
	toSerialize["steamImgURL"] = o.SteamImgURL.Get()
	toSerialize["residence"] = o.Residence.Get()
	toSerialize["userName"] = o.UserName.Get()
	toSerialize["kontorActivated"] = o.KontorActivated
	toSerialize["changelogVisible"] = o.ChangelogVisible
	toSerialize["deletionFrist"] = o.DeletionFrist
	toSerialize["tfaActivated"] = o.TfaActivated
	toSerialize["isAlphaTester"] = o.IsAlphaTester
	toSerialize["isTrustedUser"] = o.IsTrustedUser
	toSerialize["systemAdminPermissions"] = o.SystemAdminPermissions
	toSerialize["systemAdminRankName"] = o.SystemAdminRankName.Get()
	toSerialize["twitchName"] = o.TwitchName.Get()
	toSerialize["twitchID"] = o.TwitchID.Get()
	toSerialize["discordUID"] = o.DiscordUID.Get()
	toSerialize["spedition"] = o.Spedition.Get()
	toSerialize["rank"] = o.Rank.Get()
	if o.Achievements != nil {
		toSerialize["achievements"] = o.Achievements
	}
	toSerialize["inSped"] = o.InSped
	toSerialize["formatName"] = o.FormatName.Get()
	toSerialize["lastTaskTime"] = o.LastTaskTime
	toSerialize["isInCooldown"] = o.IsInCooldown
	toSerialize["mainBankAccount"] = o.MainBankAccount.Get()
	toSerialize["speditionJoinDate"] = o.SpeditionJoinDate.Get()
	return toSerialize, nil
}

func (o *FPHSpedVAPIObjectsUsersFullUserInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"steamID",
		"authCode",
		"plusUntil",
		"plusActive",
		"bannedTill",
		"isBanned",
		"bannedReason",
		"eMail",
		"realName",
		"aboutMe",
		"birthday",
		"steamImgURL",
		"residence",
		"userName",
		"kontorActivated",
		"changelogVisible",
		"deletionFrist",
		"tfaActivated",
		"isAlphaTester",
		"isTrustedUser",
		"systemAdminPermissions",
		"systemAdminRankName",
		"twitchName",
		"twitchID",
		"discordUID",
		"spedition",
		"rank",
		"achievements",
		"inSped",
		"formatName",
		"lastTaskTime",
		"isInCooldown",
		"mainBankAccount",
		"speditionJoinDate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFPHSpedVAPIObjectsUsersFullUserInfo := _FPHSpedVAPIObjectsUsersFullUserInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFPHSpedVAPIObjectsUsersFullUserInfo)

	if err != nil {
		return err
	}

	*o = FPHSpedVAPIObjectsUsersFullUserInfo(varFPHSpedVAPIObjectsUsersFullUserInfo)

	return err
}

type NullableFPHSpedVAPIObjectsUsersFullUserInfo struct {
	value *FPHSpedVAPIObjectsUsersFullUserInfo
	isSet bool
}

func (v NullableFPHSpedVAPIObjectsUsersFullUserInfo) Get() *FPHSpedVAPIObjectsUsersFullUserInfo {
	return v.value
}

func (v *NullableFPHSpedVAPIObjectsUsersFullUserInfo) Set(val *FPHSpedVAPIObjectsUsersFullUserInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableFPHSpedVAPIObjectsUsersFullUserInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableFPHSpedVAPIObjectsUsersFullUserInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFPHSpedVAPIObjectsUsersFullUserInfo(val *FPHSpedVAPIObjectsUsersFullUserInfo) *NullableFPHSpedVAPIObjectsUsersFullUserInfo {
	return &NullableFPHSpedVAPIObjectsUsersFullUserInfo{value: val, isSet: true}
}

func (v NullableFPHSpedVAPIObjectsUsersFullUserInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFPHSpedVAPIObjectsUsersFullUserInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


