/*
SpedV API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FPHSpedVAPIObjectsSpeditionsTruckType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FPHSpedVAPIObjectsSpeditionsTruckType{}

// FPHSpedVAPIObjectsSpeditionsTruckType struct for FPHSpedVAPIObjectsSpeditionsTruckType
type FPHSpedVAPIObjectsSpeditionsTruckType struct {
	Id int32 `json:"id"`
	Manufactor NullableString `json:"manufactor"`
	Model NullableString `json:"model"`
	//   0 = ETS2  1 = ATS  -1 = NotSet
	Game FPHSpedVAPIEnumsGameEnum `json:"game"`
	Price int32 `json:"price"`
	RentPrice int32 `json:"rentPrice"`
}

type _FPHSpedVAPIObjectsSpeditionsTruckType FPHSpedVAPIObjectsSpeditionsTruckType

// NewFPHSpedVAPIObjectsSpeditionsTruckType instantiates a new FPHSpedVAPIObjectsSpeditionsTruckType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFPHSpedVAPIObjectsSpeditionsTruckType(id int32, manufactor NullableString, model NullableString, game FPHSpedVAPIEnumsGameEnum, price int32, rentPrice int32) *FPHSpedVAPIObjectsSpeditionsTruckType {
	this := FPHSpedVAPIObjectsSpeditionsTruckType{}
	this.Id = id
	this.Manufactor = manufactor
	this.Model = model
	this.Game = game
	this.Price = price
	this.RentPrice = rentPrice
	return &this
}

// NewFPHSpedVAPIObjectsSpeditionsTruckTypeWithDefaults instantiates a new FPHSpedVAPIObjectsSpeditionsTruckType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFPHSpedVAPIObjectsSpeditionsTruckTypeWithDefaults() *FPHSpedVAPIObjectsSpeditionsTruckType {
	this := FPHSpedVAPIObjectsSpeditionsTruckType{}
	return &this
}

// GetId returns the Id field value
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) SetId(v int32) {
	o.Id = v
}

// GetManufactor returns the Manufactor field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) GetManufactor() string {
	if o == nil || o.Manufactor.Get() == nil {
		var ret string
		return ret
	}

	return *o.Manufactor.Get()
}

// GetManufactorOk returns a tuple with the Manufactor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) GetManufactorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Manufactor.Get(), o.Manufactor.IsSet()
}

// SetManufactor sets field value
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) SetManufactor(v string) {
	o.Manufactor.Set(&v)
}

// GetModel returns the Model field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) GetModel() string {
	if o == nil || o.Model.Get() == nil {
		var ret string
		return ret
	}

	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// SetModel sets field value
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) SetModel(v string) {
	o.Model.Set(&v)
}

// GetGame returns the Game field value
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) GetGame() FPHSpedVAPIEnumsGameEnum {
	if o == nil {
		var ret FPHSpedVAPIEnumsGameEnum
		return ret
	}

	return o.Game
}

// GetGameOk returns a tuple with the Game field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) GetGameOk() (*FPHSpedVAPIEnumsGameEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Game, true
}

// SetGame sets field value
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) SetGame(v FPHSpedVAPIEnumsGameEnum) {
	o.Game = v
}

// GetPrice returns the Price field value
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) GetPrice() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) GetPriceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) SetPrice(v int32) {
	o.Price = v
}

// GetRentPrice returns the RentPrice field value
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) GetRentPrice() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RentPrice
}

// GetRentPriceOk returns a tuple with the RentPrice field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) GetRentPriceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RentPrice, true
}

// SetRentPrice sets field value
func (o *FPHSpedVAPIObjectsSpeditionsTruckType) SetRentPrice(v int32) {
	o.RentPrice = v
}

func (o FPHSpedVAPIObjectsSpeditionsTruckType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FPHSpedVAPIObjectsSpeditionsTruckType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["manufactor"] = o.Manufactor.Get()
	toSerialize["model"] = o.Model.Get()
	toSerialize["game"] = o.Game
	toSerialize["price"] = o.Price
	toSerialize["rentPrice"] = o.RentPrice
	return toSerialize, nil
}

func (o *FPHSpedVAPIObjectsSpeditionsTruckType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"manufactor",
		"model",
		"game",
		"price",
		"rentPrice",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFPHSpedVAPIObjectsSpeditionsTruckType := _FPHSpedVAPIObjectsSpeditionsTruckType{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFPHSpedVAPIObjectsSpeditionsTruckType)

	if err != nil {
		return err
	}

	*o = FPHSpedVAPIObjectsSpeditionsTruckType(varFPHSpedVAPIObjectsSpeditionsTruckType)

	return err
}

type NullableFPHSpedVAPIObjectsSpeditionsTruckType struct {
	value *FPHSpedVAPIObjectsSpeditionsTruckType
	isSet bool
}

func (v NullableFPHSpedVAPIObjectsSpeditionsTruckType) Get() *FPHSpedVAPIObjectsSpeditionsTruckType {
	return v.value
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsTruckType) Set(val *FPHSpedVAPIObjectsSpeditionsTruckType) {
	v.value = val
	v.isSet = true
}

func (v NullableFPHSpedVAPIObjectsSpeditionsTruckType) IsSet() bool {
	return v.isSet
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsTruckType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFPHSpedVAPIObjectsSpeditionsTruckType(val *FPHSpedVAPIObjectsSpeditionsTruckType) *NullableFPHSpedVAPIObjectsSpeditionsTruckType {
	return &NullableFPHSpedVAPIObjectsSpeditionsTruckType{value: val, isSet: true}
}

func (v NullableFPHSpedVAPIObjectsSpeditionsTruckType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsTruckType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


