/*
SpedV API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FPHSpedVAPIObjectsSpeditionsRank type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FPHSpedVAPIObjectsSpeditionsRank{}

// FPHSpedVAPIObjectsSpeditionsRank struct for FPHSpedVAPIObjectsSpeditionsRank
type FPHSpedVAPIObjectsSpeditionsRank struct {
	Id int32 `json:"id"`
	Name NullableString `json:"name"`
	Salary int32 `json:"salary"`
	KmSalary float64 `json:"kmSalary"`
	Sorting int32 `json:"sorting"`
	IsStartUpRank bool `json:"isStartUpRank"`
	IsLeader bool `json:"isLeader"`
	IsInactiveRank bool `json:"isInactiveRank"`
	InactiveTime int32 `json:"inactiveTime"`
	Color NullableString `json:"color"`
	RankPermissions []FPHSpedVAPIObjectsSpeditionsRankPermission `json:"rankPermissions"`
}

type _FPHSpedVAPIObjectsSpeditionsRank FPHSpedVAPIObjectsSpeditionsRank

// NewFPHSpedVAPIObjectsSpeditionsRank instantiates a new FPHSpedVAPIObjectsSpeditionsRank object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFPHSpedVAPIObjectsSpeditionsRank(id int32, name NullableString, salary int32, kmSalary float64, sorting int32, isStartUpRank bool, isLeader bool, isInactiveRank bool, inactiveTime int32, color NullableString, rankPermissions []FPHSpedVAPIObjectsSpeditionsRankPermission) *FPHSpedVAPIObjectsSpeditionsRank {
	this := FPHSpedVAPIObjectsSpeditionsRank{}
	this.Id = id
	this.Name = name
	this.Salary = salary
	this.KmSalary = kmSalary
	this.Sorting = sorting
	this.IsStartUpRank = isStartUpRank
	this.IsLeader = isLeader
	this.IsInactiveRank = isInactiveRank
	this.InactiveTime = inactiveTime
	this.Color = color
	this.RankPermissions = rankPermissions
	return &this
}

// NewFPHSpedVAPIObjectsSpeditionsRankWithDefaults instantiates a new FPHSpedVAPIObjectsSpeditionsRank object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFPHSpedVAPIObjectsSpeditionsRankWithDefaults() *FPHSpedVAPIObjectsSpeditionsRank {
	this := FPHSpedVAPIObjectsSpeditionsRank{}
	return &this
}

// GetId returns the Id field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) SetName(v string) {
	o.Name.Set(&v)
}

// GetSalary returns the Salary field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetSalary() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Salary
}

// GetSalaryOk returns a tuple with the Salary field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetSalaryOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Salary, true
}

// SetSalary sets field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) SetSalary(v int32) {
	o.Salary = v
}

// GetKmSalary returns the KmSalary field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetKmSalary() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.KmSalary
}

// GetKmSalaryOk returns a tuple with the KmSalary field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetKmSalaryOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KmSalary, true
}

// SetKmSalary sets field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) SetKmSalary(v float64) {
	o.KmSalary = v
}

// GetSorting returns the Sorting field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetSorting() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Sorting
}

// GetSortingOk returns a tuple with the Sorting field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetSortingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sorting, true
}

// SetSorting sets field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) SetSorting(v int32) {
	o.Sorting = v
}

// GetIsStartUpRank returns the IsStartUpRank field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetIsStartUpRank() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsStartUpRank
}

// GetIsStartUpRankOk returns a tuple with the IsStartUpRank field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetIsStartUpRankOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsStartUpRank, true
}

// SetIsStartUpRank sets field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) SetIsStartUpRank(v bool) {
	o.IsStartUpRank = v
}

// GetIsLeader returns the IsLeader field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetIsLeader() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsLeader
}

// GetIsLeaderOk returns a tuple with the IsLeader field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetIsLeaderOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsLeader, true
}

// SetIsLeader sets field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) SetIsLeader(v bool) {
	o.IsLeader = v
}

// GetIsInactiveRank returns the IsInactiveRank field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetIsInactiveRank() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsInactiveRank
}

// GetIsInactiveRankOk returns a tuple with the IsInactiveRank field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetIsInactiveRankOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsInactiveRank, true
}

// SetIsInactiveRank sets field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) SetIsInactiveRank(v bool) {
	o.IsInactiveRank = v
}

// GetInactiveTime returns the InactiveTime field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetInactiveTime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InactiveTime
}

// GetInactiveTimeOk returns a tuple with the InactiveTime field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetInactiveTimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InactiveTime, true
}

// SetInactiveTime sets field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) SetInactiveTime(v int32) {
	o.InactiveTime = v
}

// GetColor returns the Color field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetColor() string {
	if o == nil || o.Color.Get() == nil {
		var ret string
		return ret
	}

	return *o.Color.Get()
}

// GetColorOk returns a tuple with the Color field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Color.Get(), o.Color.IsSet()
}

// SetColor sets field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) SetColor(v string) {
	o.Color.Set(&v)
}

// GetRankPermissions returns the RankPermissions field value
// If the value is explicit nil, the zero value for []FPHSpedVAPIObjectsSpeditionsRankPermission will be returned
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetRankPermissions() []FPHSpedVAPIObjectsSpeditionsRankPermission {
	if o == nil {
		var ret []FPHSpedVAPIObjectsSpeditionsRankPermission
		return ret
	}

	return o.RankPermissions
}

// GetRankPermissionsOk returns a tuple with the RankPermissions field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsRank) GetRankPermissionsOk() ([]FPHSpedVAPIObjectsSpeditionsRankPermission, bool) {
	if o == nil || IsNil(o.RankPermissions) {
		return nil, false
	}
	return o.RankPermissions, true
}

// SetRankPermissions sets field value
func (o *FPHSpedVAPIObjectsSpeditionsRank) SetRankPermissions(v []FPHSpedVAPIObjectsSpeditionsRankPermission) {
	o.RankPermissions = v
}

func (o FPHSpedVAPIObjectsSpeditionsRank) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FPHSpedVAPIObjectsSpeditionsRank) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name.Get()
	toSerialize["salary"] = o.Salary
	toSerialize["kmSalary"] = o.KmSalary
	toSerialize["sorting"] = o.Sorting
	toSerialize["isStartUpRank"] = o.IsStartUpRank
	toSerialize["isLeader"] = o.IsLeader
	toSerialize["isInactiveRank"] = o.IsInactiveRank
	toSerialize["inactiveTime"] = o.InactiveTime
	toSerialize["color"] = o.Color.Get()
	if o.RankPermissions != nil {
		toSerialize["rankPermissions"] = o.RankPermissions
	}
	return toSerialize, nil
}

func (o *FPHSpedVAPIObjectsSpeditionsRank) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"salary",
		"kmSalary",
		"sorting",
		"isStartUpRank",
		"isLeader",
		"isInactiveRank",
		"inactiveTime",
		"color",
		"rankPermissions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFPHSpedVAPIObjectsSpeditionsRank := _FPHSpedVAPIObjectsSpeditionsRank{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFPHSpedVAPIObjectsSpeditionsRank)

	if err != nil {
		return err
	}

	*o = FPHSpedVAPIObjectsSpeditionsRank(varFPHSpedVAPIObjectsSpeditionsRank)

	return err
}

type NullableFPHSpedVAPIObjectsSpeditionsRank struct {
	value *FPHSpedVAPIObjectsSpeditionsRank
	isSet bool
}

func (v NullableFPHSpedVAPIObjectsSpeditionsRank) Get() *FPHSpedVAPIObjectsSpeditionsRank {
	return v.value
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsRank) Set(val *FPHSpedVAPIObjectsSpeditionsRank) {
	v.value = val
	v.isSet = true
}

func (v NullableFPHSpedVAPIObjectsSpeditionsRank) IsSet() bool {
	return v.isSet
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsRank) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFPHSpedVAPIObjectsSpeditionsRank(val *FPHSpedVAPIObjectsSpeditionsRank) *NullableFPHSpedVAPIObjectsSpeditionsRank {
	return &NullableFPHSpedVAPIObjectsSpeditionsRank{value: val, isSet: true}
}

func (v NullableFPHSpedVAPIObjectsSpeditionsRank) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsRank) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


