/*
SpedV API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FPHSpedVAPIObjectsChatSystemChatParticipant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FPHSpedVAPIObjectsChatSystemChatParticipant{}

// FPHSpedVAPIObjectsChatSystemChatParticipant struct for FPHSpedVAPIObjectsChatSystemChatParticipant
type FPHSpedVAPIObjectsChatSystemChatParticipant struct {
	User NullableFPHSpedVAPIObjectsUsersUser `json:"user"`
	HasArchived bool `json:"hasArchived"`
	LastView time.Time `json:"lastView"`
	IsAdmin bool `json:"isAdmin"`
}

type _FPHSpedVAPIObjectsChatSystemChatParticipant FPHSpedVAPIObjectsChatSystemChatParticipant

// NewFPHSpedVAPIObjectsChatSystemChatParticipant instantiates a new FPHSpedVAPIObjectsChatSystemChatParticipant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFPHSpedVAPIObjectsChatSystemChatParticipant(user NullableFPHSpedVAPIObjectsUsersUser, hasArchived bool, lastView time.Time, isAdmin bool) *FPHSpedVAPIObjectsChatSystemChatParticipant {
	this := FPHSpedVAPIObjectsChatSystemChatParticipant{}
	this.User = user
	this.HasArchived = hasArchived
	this.LastView = lastView
	this.IsAdmin = isAdmin
	return &this
}

// NewFPHSpedVAPIObjectsChatSystemChatParticipantWithDefaults instantiates a new FPHSpedVAPIObjectsChatSystemChatParticipant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFPHSpedVAPIObjectsChatSystemChatParticipantWithDefaults() *FPHSpedVAPIObjectsChatSystemChatParticipant {
	this := FPHSpedVAPIObjectsChatSystemChatParticipant{}
	return &this
}

// GetUser returns the User field value
// If the value is explicit nil, the zero value for FPHSpedVAPIObjectsUsersUser will be returned
func (o *FPHSpedVAPIObjectsChatSystemChatParticipant) GetUser() FPHSpedVAPIObjectsUsersUser {
	if o == nil || o.User.Get() == nil {
		var ret FPHSpedVAPIObjectsUsersUser
		return ret
	}

	return *o.User.Get()
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsChatSystemChatParticipant) GetUserOk() (*FPHSpedVAPIObjectsUsersUser, bool) {
	if o == nil {
		return nil, false
	}
	return o.User.Get(), o.User.IsSet()
}

// SetUser sets field value
func (o *FPHSpedVAPIObjectsChatSystemChatParticipant) SetUser(v FPHSpedVAPIObjectsUsersUser) {
	o.User.Set(&v)
}

// GetHasArchived returns the HasArchived field value
func (o *FPHSpedVAPIObjectsChatSystemChatParticipant) GetHasArchived() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasArchived
}

// GetHasArchivedOk returns a tuple with the HasArchived field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsChatSystemChatParticipant) GetHasArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasArchived, true
}

// SetHasArchived sets field value
func (o *FPHSpedVAPIObjectsChatSystemChatParticipant) SetHasArchived(v bool) {
	o.HasArchived = v
}

// GetLastView returns the LastView field value
func (o *FPHSpedVAPIObjectsChatSystemChatParticipant) GetLastView() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastView
}

// GetLastViewOk returns a tuple with the LastView field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsChatSystemChatParticipant) GetLastViewOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastView, true
}

// SetLastView sets field value
func (o *FPHSpedVAPIObjectsChatSystemChatParticipant) SetLastView(v time.Time) {
	o.LastView = v
}

// GetIsAdmin returns the IsAdmin field value
func (o *FPHSpedVAPIObjectsChatSystemChatParticipant) GetIsAdmin() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsAdmin
}

// GetIsAdminOk returns a tuple with the IsAdmin field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsChatSystemChatParticipant) GetIsAdminOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsAdmin, true
}

// SetIsAdmin sets field value
func (o *FPHSpedVAPIObjectsChatSystemChatParticipant) SetIsAdmin(v bool) {
	o.IsAdmin = v
}

func (o FPHSpedVAPIObjectsChatSystemChatParticipant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FPHSpedVAPIObjectsChatSystemChatParticipant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user"] = o.User.Get()
	toSerialize["hasArchived"] = o.HasArchived
	toSerialize["lastView"] = o.LastView
	toSerialize["isAdmin"] = o.IsAdmin
	return toSerialize, nil
}

func (o *FPHSpedVAPIObjectsChatSystemChatParticipant) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user",
		"hasArchived",
		"lastView",
		"isAdmin",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFPHSpedVAPIObjectsChatSystemChatParticipant := _FPHSpedVAPIObjectsChatSystemChatParticipant{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFPHSpedVAPIObjectsChatSystemChatParticipant)

	if err != nil {
		return err
	}

	*o = FPHSpedVAPIObjectsChatSystemChatParticipant(varFPHSpedVAPIObjectsChatSystemChatParticipant)

	return err
}

type NullableFPHSpedVAPIObjectsChatSystemChatParticipant struct {
	value *FPHSpedVAPIObjectsChatSystemChatParticipant
	isSet bool
}

func (v NullableFPHSpedVAPIObjectsChatSystemChatParticipant) Get() *FPHSpedVAPIObjectsChatSystemChatParticipant {
	return v.value
}

func (v *NullableFPHSpedVAPIObjectsChatSystemChatParticipant) Set(val *FPHSpedVAPIObjectsChatSystemChatParticipant) {
	v.value = val
	v.isSet = true
}

func (v NullableFPHSpedVAPIObjectsChatSystemChatParticipant) IsSet() bool {
	return v.isSet
}

func (v *NullableFPHSpedVAPIObjectsChatSystemChatParticipant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFPHSpedVAPIObjectsChatSystemChatParticipant(val *FPHSpedVAPIObjectsChatSystemChatParticipant) *NullableFPHSpedVAPIObjectsChatSystemChatParticipant {
	return &NullableFPHSpedVAPIObjectsChatSystemChatParticipant{value: val, isSet: true}
}

func (v NullableFPHSpedVAPIObjectsChatSystemChatParticipant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFPHSpedVAPIObjectsChatSystemChatParticipant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


