/*
SpedV API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo{}

// FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo struct for FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo
type FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo struct {
	Id int32 `json:"id"`
	Name NullableString `json:"name"`
	ShortName NullableString `json:"shortName"`
	ApplImg NullableString `json:"applImg"`
	ApplText NullableString `json:"applText"`
	AdminAnnounce NullableString `json:"adminAnnounce"`
	DiscordWebHook NullableString `json:"discordWebHook"`
	Expenses int32 `json:"expenses"`
	MaxTruckPerUser int32 `json:"maxTruckPerUser"`
	MaxAllowedVelocity int32 `json:"maxAllowedVelocity"`
	MaxAllowedVelocityATS int32 `json:"maxAllowedVelocityATS"`
	DmgReportFromPercent int32 `json:"dmgReportFromPercent"`
	MinCoolDown float64 `json:"minCoolDown"`
	CoolDown float64 `json:"coolDown"`
	//   0 = NonCompeting  1 = LightRealism  2 = RealEco  -1 = NotSet
	SpeditionType FPHSpedVAPIEnumsSpeditionType `json:"speditionType"`
	IsVisible bool `json:"isVisible"`
	AcceptsApplicants bool `json:"acceptsApplicants"`
	OneTimeJoinPasswords []string `json:"oneTimeJoinPasswords"`
	SpeditionFounder NullableFPHSpedVAPIObjectsUsersUser `json:"speditionFounder"`
	ColorCollections []FPHSpedVAPIObjectsSaveGameSaveGameColor `json:"colorCollections"`
}

type _FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo

// NewFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo instantiates a new FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo(id int32, name NullableString, shortName NullableString, applImg NullableString, applText NullableString, adminAnnounce NullableString, discordWebHook NullableString, expenses int32, maxTruckPerUser int32, maxAllowedVelocity int32, maxAllowedVelocityATS int32, dmgReportFromPercent int32, minCoolDown float64, coolDown float64, speditionType FPHSpedVAPIEnumsSpeditionType, isVisible bool, acceptsApplicants bool, oneTimeJoinPasswords []string, speditionFounder NullableFPHSpedVAPIObjectsUsersUser, colorCollections []FPHSpedVAPIObjectsSaveGameSaveGameColor) *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo {
	this := FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo{}
	this.Id = id
	this.Name = name
	this.ShortName = shortName
	this.ApplImg = applImg
	this.ApplText = applText
	this.AdminAnnounce = adminAnnounce
	this.DiscordWebHook = discordWebHook
	this.Expenses = expenses
	this.MaxTruckPerUser = maxTruckPerUser
	this.MaxAllowedVelocity = maxAllowedVelocity
	this.MaxAllowedVelocityATS = maxAllowedVelocityATS
	this.DmgReportFromPercent = dmgReportFromPercent
	this.MinCoolDown = minCoolDown
	this.CoolDown = coolDown
	this.SpeditionType = speditionType
	this.IsVisible = isVisible
	this.AcceptsApplicants = acceptsApplicants
	this.OneTimeJoinPasswords = oneTimeJoinPasswords
	this.SpeditionFounder = speditionFounder
	this.ColorCollections = colorCollections
	return &this
}

// NewFPHSpedVAPIObjectsSpeditionsFullSpeditionInfoWithDefaults instantiates a new FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFPHSpedVAPIObjectsSpeditionsFullSpeditionInfoWithDefaults() *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo {
	this := FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo{}
	return &this
}

// GetId returns the Id field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetName(v string) {
	o.Name.Set(&v)
}

// GetShortName returns the ShortName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetShortName() string {
	if o == nil || o.ShortName.Get() == nil {
		var ret string
		return ret
	}

	return *o.ShortName.Get()
}

// GetShortNameOk returns a tuple with the ShortName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetShortNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShortName.Get(), o.ShortName.IsSet()
}

// SetShortName sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetShortName(v string) {
	o.ShortName.Set(&v)
}

// GetApplImg returns the ApplImg field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetApplImg() string {
	if o == nil || o.ApplImg.Get() == nil {
		var ret string
		return ret
	}

	return *o.ApplImg.Get()
}

// GetApplImgOk returns a tuple with the ApplImg field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetApplImgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApplImg.Get(), o.ApplImg.IsSet()
}

// SetApplImg sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetApplImg(v string) {
	o.ApplImg.Set(&v)
}

// GetApplText returns the ApplText field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetApplText() string {
	if o == nil || o.ApplText.Get() == nil {
		var ret string
		return ret
	}

	return *o.ApplText.Get()
}

// GetApplTextOk returns a tuple with the ApplText field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetApplTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApplText.Get(), o.ApplText.IsSet()
}

// SetApplText sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetApplText(v string) {
	o.ApplText.Set(&v)
}

// GetAdminAnnounce returns the AdminAnnounce field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetAdminAnnounce() string {
	if o == nil || o.AdminAnnounce.Get() == nil {
		var ret string
		return ret
	}

	return *o.AdminAnnounce.Get()
}

// GetAdminAnnounceOk returns a tuple with the AdminAnnounce field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetAdminAnnounceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AdminAnnounce.Get(), o.AdminAnnounce.IsSet()
}

// SetAdminAnnounce sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetAdminAnnounce(v string) {
	o.AdminAnnounce.Set(&v)
}

// GetDiscordWebHook returns the DiscordWebHook field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetDiscordWebHook() string {
	if o == nil || o.DiscordWebHook.Get() == nil {
		var ret string
		return ret
	}

	return *o.DiscordWebHook.Get()
}

// GetDiscordWebHookOk returns a tuple with the DiscordWebHook field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetDiscordWebHookOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DiscordWebHook.Get(), o.DiscordWebHook.IsSet()
}

// SetDiscordWebHook sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetDiscordWebHook(v string) {
	o.DiscordWebHook.Set(&v)
}

// GetExpenses returns the Expenses field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetExpenses() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Expenses
}

// GetExpensesOk returns a tuple with the Expenses field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetExpensesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expenses, true
}

// SetExpenses sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetExpenses(v int32) {
	o.Expenses = v
}

// GetMaxTruckPerUser returns the MaxTruckPerUser field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetMaxTruckPerUser() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxTruckPerUser
}

// GetMaxTruckPerUserOk returns a tuple with the MaxTruckPerUser field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetMaxTruckPerUserOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxTruckPerUser, true
}

// SetMaxTruckPerUser sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetMaxTruckPerUser(v int32) {
	o.MaxTruckPerUser = v
}

// GetMaxAllowedVelocity returns the MaxAllowedVelocity field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetMaxAllowedVelocity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxAllowedVelocity
}

// GetMaxAllowedVelocityOk returns a tuple with the MaxAllowedVelocity field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetMaxAllowedVelocityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxAllowedVelocity, true
}

// SetMaxAllowedVelocity sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetMaxAllowedVelocity(v int32) {
	o.MaxAllowedVelocity = v
}

// GetMaxAllowedVelocityATS returns the MaxAllowedVelocityATS field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetMaxAllowedVelocityATS() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxAllowedVelocityATS
}

// GetMaxAllowedVelocityATSOk returns a tuple with the MaxAllowedVelocityATS field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetMaxAllowedVelocityATSOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxAllowedVelocityATS, true
}

// SetMaxAllowedVelocityATS sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetMaxAllowedVelocityATS(v int32) {
	o.MaxAllowedVelocityATS = v
}

// GetDmgReportFromPercent returns the DmgReportFromPercent field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetDmgReportFromPercent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DmgReportFromPercent
}

// GetDmgReportFromPercentOk returns a tuple with the DmgReportFromPercent field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetDmgReportFromPercentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DmgReportFromPercent, true
}

// SetDmgReportFromPercent sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetDmgReportFromPercent(v int32) {
	o.DmgReportFromPercent = v
}

// GetMinCoolDown returns the MinCoolDown field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetMinCoolDown() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MinCoolDown
}

// GetMinCoolDownOk returns a tuple with the MinCoolDown field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetMinCoolDownOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinCoolDown, true
}

// SetMinCoolDown sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetMinCoolDown(v float64) {
	o.MinCoolDown = v
}

// GetCoolDown returns the CoolDown field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetCoolDown() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.CoolDown
}

// GetCoolDownOk returns a tuple with the CoolDown field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetCoolDownOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CoolDown, true
}

// SetCoolDown sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetCoolDown(v float64) {
	o.CoolDown = v
}

// GetSpeditionType returns the SpeditionType field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetSpeditionType() FPHSpedVAPIEnumsSpeditionType {
	if o == nil {
		var ret FPHSpedVAPIEnumsSpeditionType
		return ret
	}

	return o.SpeditionType
}

// GetSpeditionTypeOk returns a tuple with the SpeditionType field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetSpeditionTypeOk() (*FPHSpedVAPIEnumsSpeditionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpeditionType, true
}

// SetSpeditionType sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetSpeditionType(v FPHSpedVAPIEnumsSpeditionType) {
	o.SpeditionType = v
}

// GetIsVisible returns the IsVisible field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetIsVisible() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsVisible
}

// GetIsVisibleOk returns a tuple with the IsVisible field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetIsVisibleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsVisible, true
}

// SetIsVisible sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetIsVisible(v bool) {
	o.IsVisible = v
}

// GetAcceptsApplicants returns the AcceptsApplicants field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetAcceptsApplicants() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AcceptsApplicants
}

// GetAcceptsApplicantsOk returns a tuple with the AcceptsApplicants field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetAcceptsApplicantsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AcceptsApplicants, true
}

// SetAcceptsApplicants sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetAcceptsApplicants(v bool) {
	o.AcceptsApplicants = v
}

// GetOneTimeJoinPasswords returns the OneTimeJoinPasswords field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetOneTimeJoinPasswords() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.OneTimeJoinPasswords
}

// GetOneTimeJoinPasswordsOk returns a tuple with the OneTimeJoinPasswords field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetOneTimeJoinPasswordsOk() ([]string, bool) {
	if o == nil || IsNil(o.OneTimeJoinPasswords) {
		return nil, false
	}
	return o.OneTimeJoinPasswords, true
}

// SetOneTimeJoinPasswords sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetOneTimeJoinPasswords(v []string) {
	o.OneTimeJoinPasswords = v
}

// GetSpeditionFounder returns the SpeditionFounder field value
// If the value is explicit nil, the zero value for FPHSpedVAPIObjectsUsersUser will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetSpeditionFounder() FPHSpedVAPIObjectsUsersUser {
	if o == nil || o.SpeditionFounder.Get() == nil {
		var ret FPHSpedVAPIObjectsUsersUser
		return ret
	}

	return *o.SpeditionFounder.Get()
}

// GetSpeditionFounderOk returns a tuple with the SpeditionFounder field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetSpeditionFounderOk() (*FPHSpedVAPIObjectsUsersUser, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpeditionFounder.Get(), o.SpeditionFounder.IsSet()
}

// SetSpeditionFounder sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetSpeditionFounder(v FPHSpedVAPIObjectsUsersUser) {
	o.SpeditionFounder.Set(&v)
}

// GetColorCollections returns the ColorCollections field value
// If the value is explicit nil, the zero value for []FPHSpedVAPIObjectsSaveGameSaveGameColor will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetColorCollections() []FPHSpedVAPIObjectsSaveGameSaveGameColor {
	if o == nil {
		var ret []FPHSpedVAPIObjectsSaveGameSaveGameColor
		return ret
	}

	return o.ColorCollections
}

// GetColorCollectionsOk returns a tuple with the ColorCollections field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) GetColorCollectionsOk() ([]FPHSpedVAPIObjectsSaveGameSaveGameColor, bool) {
	if o == nil || IsNil(o.ColorCollections) {
		return nil, false
	}
	return o.ColorCollections, true
}

// SetColorCollections sets field value
func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) SetColorCollections(v []FPHSpedVAPIObjectsSaveGameSaveGameColor) {
	o.ColorCollections = v
}

func (o FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name.Get()
	toSerialize["shortName"] = o.ShortName.Get()
	toSerialize["applImg"] = o.ApplImg.Get()
	toSerialize["applText"] = o.ApplText.Get()
	toSerialize["adminAnnounce"] = o.AdminAnnounce.Get()
	toSerialize["discordWebHook"] = o.DiscordWebHook.Get()
	toSerialize["expenses"] = o.Expenses
	toSerialize["maxTruckPerUser"] = o.MaxTruckPerUser
	toSerialize["maxAllowedVelocity"] = o.MaxAllowedVelocity
	toSerialize["maxAllowedVelocityATS"] = o.MaxAllowedVelocityATS
	toSerialize["dmgReportFromPercent"] = o.DmgReportFromPercent
	toSerialize["minCoolDown"] = o.MinCoolDown
	toSerialize["coolDown"] = o.CoolDown
	toSerialize["speditionType"] = o.SpeditionType
	toSerialize["isVisible"] = o.IsVisible
	toSerialize["acceptsApplicants"] = o.AcceptsApplicants
	if o.OneTimeJoinPasswords != nil {
		toSerialize["oneTimeJoinPasswords"] = o.OneTimeJoinPasswords
	}
	toSerialize["speditionFounder"] = o.SpeditionFounder.Get()
	if o.ColorCollections != nil {
		toSerialize["colorCollections"] = o.ColorCollections
	}
	return toSerialize, nil
}

func (o *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"shortName",
		"applImg",
		"applText",
		"adminAnnounce",
		"discordWebHook",
		"expenses",
		"maxTruckPerUser",
		"maxAllowedVelocity",
		"maxAllowedVelocityATS",
		"dmgReportFromPercent",
		"minCoolDown",
		"coolDown",
		"speditionType",
		"isVisible",
		"acceptsApplicants",
		"oneTimeJoinPasswords",
		"speditionFounder",
		"colorCollections",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo := _FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo)

	if err != nil {
		return err
	}

	*o = FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo(varFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo)

	return err
}

type NullableFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo struct {
	value *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo
	isSet bool
}

func (v NullableFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) Get() *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo {
	return v.value
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) Set(val *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo(val *FPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) *NullableFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo {
	return &NullableFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo{value: val, isSet: true}
}

func (v NullableFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFPHSpedVAPIObjectsSpeditionsFullSpeditionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


