/*
SpedV API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FPHSpedVAPIObjectsOMSITour type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FPHSpedVAPIObjectsOMSITour{}

// FPHSpedVAPIObjectsOMSITour struct for FPHSpedVAPIObjectsOMSITour
type FPHSpedVAPIObjectsOMSITour struct {
	Id int32 `json:"id"`
	Line NullableString `json:"line"`
	Tour NullableString `json:"tour"`
	IsUserAllowed bool `json:"isUserAllowed"`
	Monday bool `json:"monday"`
	Tuesday bool `json:"tuesday"`
	Wednesday bool `json:"wednesday"`
	Thursday bool `json:"thursday"`
	Friday bool `json:"friday"`
	Saturday bool `json:"saturday"`
	Sunday bool `json:"sunday"`
	HolidayDay bool `json:"holidayDay"`
	School bool `json:"school"`
	Holidays bool `json:"holidays"`
}

type _FPHSpedVAPIObjectsOMSITour FPHSpedVAPIObjectsOMSITour

// NewFPHSpedVAPIObjectsOMSITour instantiates a new FPHSpedVAPIObjectsOMSITour object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFPHSpedVAPIObjectsOMSITour(id int32, line NullableString, tour NullableString, isUserAllowed bool, monday bool, tuesday bool, wednesday bool, thursday bool, friday bool, saturday bool, sunday bool, holidayDay bool, school bool, holidays bool) *FPHSpedVAPIObjectsOMSITour {
	this := FPHSpedVAPIObjectsOMSITour{}
	this.Id = id
	this.Line = line
	this.Tour = tour
	this.IsUserAllowed = isUserAllowed
	this.Monday = monday
	this.Tuesday = tuesday
	this.Wednesday = wednesday
	this.Thursday = thursday
	this.Friday = friday
	this.Saturday = saturday
	this.Sunday = sunday
	this.HolidayDay = holidayDay
	this.School = school
	this.Holidays = holidays
	return &this
}

// NewFPHSpedVAPIObjectsOMSITourWithDefaults instantiates a new FPHSpedVAPIObjectsOMSITour object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFPHSpedVAPIObjectsOMSITourWithDefaults() *FPHSpedVAPIObjectsOMSITour {
	this := FPHSpedVAPIObjectsOMSITour{}
	return &this
}

// GetId returns the Id field value
func (o *FPHSpedVAPIObjectsOMSITour) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSITour) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FPHSpedVAPIObjectsOMSITour) SetId(v int32) {
	o.Id = v
}

// GetLine returns the Line field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsOMSITour) GetLine() string {
	if o == nil || o.Line.Get() == nil {
		var ret string
		return ret
	}

	return *o.Line.Get()
}

// GetLineOk returns a tuple with the Line field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSITour) GetLineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Line.Get(), o.Line.IsSet()
}

// SetLine sets field value
func (o *FPHSpedVAPIObjectsOMSITour) SetLine(v string) {
	o.Line.Set(&v)
}

// GetTour returns the Tour field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsOMSITour) GetTour() string {
	if o == nil || o.Tour.Get() == nil {
		var ret string
		return ret
	}

	return *o.Tour.Get()
}

// GetTourOk returns a tuple with the Tour field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSITour) GetTourOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tour.Get(), o.Tour.IsSet()
}

// SetTour sets field value
func (o *FPHSpedVAPIObjectsOMSITour) SetTour(v string) {
	o.Tour.Set(&v)
}

// GetIsUserAllowed returns the IsUserAllowed field value
func (o *FPHSpedVAPIObjectsOMSITour) GetIsUserAllowed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsUserAllowed
}

// GetIsUserAllowedOk returns a tuple with the IsUserAllowed field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSITour) GetIsUserAllowedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsUserAllowed, true
}

// SetIsUserAllowed sets field value
func (o *FPHSpedVAPIObjectsOMSITour) SetIsUserAllowed(v bool) {
	o.IsUserAllowed = v
}

// GetMonday returns the Monday field value
func (o *FPHSpedVAPIObjectsOMSITour) GetMonday() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Monday
}

// GetMondayOk returns a tuple with the Monday field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSITour) GetMondayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Monday, true
}

// SetMonday sets field value
func (o *FPHSpedVAPIObjectsOMSITour) SetMonday(v bool) {
	o.Monday = v
}

// GetTuesday returns the Tuesday field value
func (o *FPHSpedVAPIObjectsOMSITour) GetTuesday() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Tuesday
}

// GetTuesdayOk returns a tuple with the Tuesday field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSITour) GetTuesdayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tuesday, true
}

// SetTuesday sets field value
func (o *FPHSpedVAPIObjectsOMSITour) SetTuesday(v bool) {
	o.Tuesday = v
}

// GetWednesday returns the Wednesday field value
func (o *FPHSpedVAPIObjectsOMSITour) GetWednesday() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Wednesday
}

// GetWednesdayOk returns a tuple with the Wednesday field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSITour) GetWednesdayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Wednesday, true
}

// SetWednesday sets field value
func (o *FPHSpedVAPIObjectsOMSITour) SetWednesday(v bool) {
	o.Wednesday = v
}

// GetThursday returns the Thursday field value
func (o *FPHSpedVAPIObjectsOMSITour) GetThursday() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Thursday
}

// GetThursdayOk returns a tuple with the Thursday field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSITour) GetThursdayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Thursday, true
}

// SetThursday sets field value
func (o *FPHSpedVAPIObjectsOMSITour) SetThursday(v bool) {
	o.Thursday = v
}

// GetFriday returns the Friday field value
func (o *FPHSpedVAPIObjectsOMSITour) GetFriday() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Friday
}

// GetFridayOk returns a tuple with the Friday field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSITour) GetFridayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Friday, true
}

// SetFriday sets field value
func (o *FPHSpedVAPIObjectsOMSITour) SetFriday(v bool) {
	o.Friday = v
}

// GetSaturday returns the Saturday field value
func (o *FPHSpedVAPIObjectsOMSITour) GetSaturday() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Saturday
}

// GetSaturdayOk returns a tuple with the Saturday field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSITour) GetSaturdayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Saturday, true
}

// SetSaturday sets field value
func (o *FPHSpedVAPIObjectsOMSITour) SetSaturday(v bool) {
	o.Saturday = v
}

// GetSunday returns the Sunday field value
func (o *FPHSpedVAPIObjectsOMSITour) GetSunday() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Sunday
}

// GetSundayOk returns a tuple with the Sunday field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSITour) GetSundayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sunday, true
}

// SetSunday sets field value
func (o *FPHSpedVAPIObjectsOMSITour) SetSunday(v bool) {
	o.Sunday = v
}

// GetHolidayDay returns the HolidayDay field value
func (o *FPHSpedVAPIObjectsOMSITour) GetHolidayDay() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HolidayDay
}

// GetHolidayDayOk returns a tuple with the HolidayDay field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSITour) GetHolidayDayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HolidayDay, true
}

// SetHolidayDay sets field value
func (o *FPHSpedVAPIObjectsOMSITour) SetHolidayDay(v bool) {
	o.HolidayDay = v
}

// GetSchool returns the School field value
func (o *FPHSpedVAPIObjectsOMSITour) GetSchool() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.School
}

// GetSchoolOk returns a tuple with the School field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSITour) GetSchoolOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.School, true
}

// SetSchool sets field value
func (o *FPHSpedVAPIObjectsOMSITour) SetSchool(v bool) {
	o.School = v
}

// GetHolidays returns the Holidays field value
func (o *FPHSpedVAPIObjectsOMSITour) GetHolidays() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Holidays
}

// GetHolidaysOk returns a tuple with the Holidays field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSITour) GetHolidaysOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Holidays, true
}

// SetHolidays sets field value
func (o *FPHSpedVAPIObjectsOMSITour) SetHolidays(v bool) {
	o.Holidays = v
}

func (o FPHSpedVAPIObjectsOMSITour) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FPHSpedVAPIObjectsOMSITour) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["line"] = o.Line.Get()
	toSerialize["tour"] = o.Tour.Get()
	toSerialize["isUserAllowed"] = o.IsUserAllowed
	toSerialize["monday"] = o.Monday
	toSerialize["tuesday"] = o.Tuesday
	toSerialize["wednesday"] = o.Wednesday
	toSerialize["thursday"] = o.Thursday
	toSerialize["friday"] = o.Friday
	toSerialize["saturday"] = o.Saturday
	toSerialize["sunday"] = o.Sunday
	toSerialize["holidayDay"] = o.HolidayDay
	toSerialize["school"] = o.School
	toSerialize["holidays"] = o.Holidays
	return toSerialize, nil
}

func (o *FPHSpedVAPIObjectsOMSITour) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"line",
		"tour",
		"isUserAllowed",
		"monday",
		"tuesday",
		"wednesday",
		"thursday",
		"friday",
		"saturday",
		"sunday",
		"holidayDay",
		"school",
		"holidays",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFPHSpedVAPIObjectsOMSITour := _FPHSpedVAPIObjectsOMSITour{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFPHSpedVAPIObjectsOMSITour)

	if err != nil {
		return err
	}

	*o = FPHSpedVAPIObjectsOMSITour(varFPHSpedVAPIObjectsOMSITour)

	return err
}

type NullableFPHSpedVAPIObjectsOMSITour struct {
	value *FPHSpedVAPIObjectsOMSITour
	isSet bool
}

func (v NullableFPHSpedVAPIObjectsOMSITour) Get() *FPHSpedVAPIObjectsOMSITour {
	return v.value
}

func (v *NullableFPHSpedVAPIObjectsOMSITour) Set(val *FPHSpedVAPIObjectsOMSITour) {
	v.value = val
	v.isSet = true
}

func (v NullableFPHSpedVAPIObjectsOMSITour) IsSet() bool {
	return v.isSet
}

func (v *NullableFPHSpedVAPIObjectsOMSITour) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFPHSpedVAPIObjectsOMSITour(val *FPHSpedVAPIObjectsOMSITour) *NullableFPHSpedVAPIObjectsOMSITour {
	return &NullableFPHSpedVAPIObjectsOMSITour{value: val, isSet: true}
}

func (v NullableFPHSpedVAPIObjectsOMSITour) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFPHSpedVAPIObjectsOMSITour) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


