/*
SpedV API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// FPHSpedVAPIEnumsSpeditionType   0 = NonCompeting  1 = LightRealism  2 = RealEco  -1 = NotSet
type FPHSpedVAPIEnumsSpeditionType int32

// List of FPH.SpedV.API.Enums.SpeditionType
const (
	_0 FPHSpedVAPIEnumsSpeditionType = 0
	_1 FPHSpedVAPIEnumsSpeditionType = 1
	_2 FPHSpedVAPIEnumsSpeditionType = 2
	_MINUS_1 FPHSpedVAPIEnumsSpeditionType = -1
)

// All allowed values of FPHSpedVAPIEnumsSpeditionType enum
var AllowedFPHSpedVAPIEnumsSpeditionTypeEnumValues = []FPHSpedVAPIEnumsSpeditionType{
	0,
	1,
	2,
	-1,
}

func (v *FPHSpedVAPIEnumsSpeditionType) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FPHSpedVAPIEnumsSpeditionType(value)
	for _, existing := range AllowedFPHSpedVAPIEnumsSpeditionTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FPHSpedVAPIEnumsSpeditionType", value)
}

// NewFPHSpedVAPIEnumsSpeditionTypeFromValue returns a pointer to a valid FPHSpedVAPIEnumsSpeditionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFPHSpedVAPIEnumsSpeditionTypeFromValue(v int32) (*FPHSpedVAPIEnumsSpeditionType, error) {
	ev := FPHSpedVAPIEnumsSpeditionType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FPHSpedVAPIEnumsSpeditionType: valid values are %v", v, AllowedFPHSpedVAPIEnumsSpeditionTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FPHSpedVAPIEnumsSpeditionType) IsValid() bool {
	for _, existing := range AllowedFPHSpedVAPIEnumsSpeditionTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to FPH.SpedV.API.Enums.SpeditionType value
func (v FPHSpedVAPIEnumsSpeditionType) Ptr() *FPHSpedVAPIEnumsSpeditionType {
	return &v
}

type NullableFPHSpedVAPIEnumsSpeditionType struct {
	value *FPHSpedVAPIEnumsSpeditionType
	isSet bool
}

func (v NullableFPHSpedVAPIEnumsSpeditionType) Get() *FPHSpedVAPIEnumsSpeditionType {
	return v.value
}

func (v *NullableFPHSpedVAPIEnumsSpeditionType) Set(val *FPHSpedVAPIEnumsSpeditionType) {
	v.value = val
	v.isSet = true
}

func (v NullableFPHSpedVAPIEnumsSpeditionType) IsSet() bool {
	return v.isSet
}

func (v *NullableFPHSpedVAPIEnumsSpeditionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFPHSpedVAPIEnumsSpeditionType(val *FPHSpedVAPIEnumsSpeditionType) *NullableFPHSpedVAPIEnumsSpeditionType {
	return &NullableFPHSpedVAPIEnumsSpeditionType{value: val, isSet: true}
}

func (v NullableFPHSpedVAPIEnumsSpeditionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFPHSpedVAPIEnumsSpeditionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

