/*
SpedV API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FPHSpedVServerObjectsSimRailSimRailDispatchStation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FPHSpedVServerObjectsSimRailSimRailDispatchStation{}

// FPHSpedVServerObjectsSimRailSimRailDispatchStation struct for FPHSpedVServerObjectsSimRailSimRailDispatchStation
type FPHSpedVServerObjectsSimRailSimRailDispatchStation struct {
	Data NullableFPHSpedVAPIObjectsSimRailSimRailDispatchStationData `json:"data,omitempty"`
}

// NewFPHSpedVServerObjectsSimRailSimRailDispatchStation instantiates a new FPHSpedVServerObjectsSimRailSimRailDispatchStation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFPHSpedVServerObjectsSimRailSimRailDispatchStation() *FPHSpedVServerObjectsSimRailSimRailDispatchStation {
	this := FPHSpedVServerObjectsSimRailSimRailDispatchStation{}
	return &this
}

// NewFPHSpedVServerObjectsSimRailSimRailDispatchStationWithDefaults instantiates a new FPHSpedVServerObjectsSimRailSimRailDispatchStation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFPHSpedVServerObjectsSimRailSimRailDispatchStationWithDefaults() *FPHSpedVServerObjectsSimRailSimRailDispatchStation {
	this := FPHSpedVServerObjectsSimRailSimRailDispatchStation{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FPHSpedVServerObjectsSimRailSimRailDispatchStation) GetData() FPHSpedVAPIObjectsSimRailSimRailDispatchStationData {
	if o == nil || IsNil(o.Data.Get()) {
		var ret FPHSpedVAPIObjectsSimRailSimRailDispatchStationData
		return ret
	}
	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVServerObjectsSimRailSimRailDispatchStation) GetDataOk() (*FPHSpedVAPIObjectsSimRailSimRailDispatchStationData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// HasData returns a boolean if a field has been set.
func (o *FPHSpedVServerObjectsSimRailSimRailDispatchStation) HasData() bool {
	if o != nil && o.Data.IsSet() {
		return true
	}

	return false
}

// SetData gets a reference to the given NullableFPHSpedVAPIObjectsSimRailSimRailDispatchStationData and assigns it to the Data field.
func (o *FPHSpedVServerObjectsSimRailSimRailDispatchStation) SetData(v FPHSpedVAPIObjectsSimRailSimRailDispatchStationData) {
	o.Data.Set(&v)
}
// SetDataNil sets the value for Data to be an explicit nil
func (o *FPHSpedVServerObjectsSimRailSimRailDispatchStation) SetDataNil() {
	o.Data.Set(nil)
}

// UnsetData ensures that no value is present for Data, not even an explicit nil
func (o *FPHSpedVServerObjectsSimRailSimRailDispatchStation) UnsetData() {
	o.Data.Unset()
}

func (o FPHSpedVServerObjectsSimRailSimRailDispatchStation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FPHSpedVServerObjectsSimRailSimRailDispatchStation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Data.IsSet() {
		toSerialize["data"] = o.Data.Get()
	}
	return toSerialize, nil
}

type NullableFPHSpedVServerObjectsSimRailSimRailDispatchStation struct {
	value *FPHSpedVServerObjectsSimRailSimRailDispatchStation
	isSet bool
}

func (v NullableFPHSpedVServerObjectsSimRailSimRailDispatchStation) Get() *FPHSpedVServerObjectsSimRailSimRailDispatchStation {
	return v.value
}

func (v *NullableFPHSpedVServerObjectsSimRailSimRailDispatchStation) Set(val *FPHSpedVServerObjectsSimRailSimRailDispatchStation) {
	v.value = val
	v.isSet = true
}

func (v NullableFPHSpedVServerObjectsSimRailSimRailDispatchStation) IsSet() bool {
	return v.isSet
}

func (v *NullableFPHSpedVServerObjectsSimRailSimRailDispatchStation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFPHSpedVServerObjectsSimRailSimRailDispatchStation(val *FPHSpedVServerObjectsSimRailSimRailDispatchStation) *NullableFPHSpedVServerObjectsSimRailSimRailDispatchStation {
	return &NullableFPHSpedVServerObjectsSimRailSimRailDispatchStation{value: val, isSet: true}
}

func (v NullableFPHSpedVServerObjectsSimRailSimRailDispatchStation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFPHSpedVServerObjectsSimRailSimRailDispatchStation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


