/*
SpedV API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FPHSpedVAPIObjectsOMSIDrivenTrip type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FPHSpedVAPIObjectsOMSIDrivenTrip{}

// FPHSpedVAPIObjectsOMSIDrivenTrip struct for FPHSpedVAPIObjectsOMSIDrivenTrip
type FPHSpedVAPIObjectsOMSIDrivenTrip struct {
	Id int32 `json:"id"`
	VisibleID NullableString `json:"visibleID"`
	StartDate time.Time `json:"startDate"`
	EndDate NullableTime `json:"endDate"`
	NeededTime NullableString `json:"neededTime"`
	BaseDate time.Time `json:"baseDate"`
	TourTrip NullableFPHSpedVAPIObjectsOMSITourTrip `json:"tourTrip"`
	Map NullableFPHSpedVAPIObjectsOMSIMap `json:"map"`
	StartKM float64 `json:"startKM"`
	EndKM NullableFloat64 `json:"endKM"`
	VisDistance NullableString `json:"visDistance"`
	Value NullableInt32 `json:"value"`
	RealtimeBoni NullableFloat64 `json:"realtimeBoni"`
	FollowupBoni NullableFloat64 `json:"followupBoni"`
	Tax NullableFloat64 `json:"tax"`
	ResultValue NullableFloat64 `json:"resultValue"`
	Currency NullableString `json:"currency"`
	//   0 = InDrive  1 = Finished  2 = Cancelled  -1 = NotAvaliable
	State FPHSpedVAPIEnumsOMSITaskState `json:"state"`
	User NullableFPHSpedVAPIObjectsUsersUser `json:"user"`
	Spedition NullableFPHSpedVAPIObjectsSpeditionsSpedition `json:"spedition"`
	RegisteredBusStops []FPHSpedVAPIObjectsOMSIDrivenTripBusStop `json:"registeredBusStops"`
}

type _FPHSpedVAPIObjectsOMSIDrivenTrip FPHSpedVAPIObjectsOMSIDrivenTrip

// NewFPHSpedVAPIObjectsOMSIDrivenTrip instantiates a new FPHSpedVAPIObjectsOMSIDrivenTrip object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFPHSpedVAPIObjectsOMSIDrivenTrip(id int32, visibleID NullableString, startDate time.Time, endDate NullableTime, neededTime NullableString, baseDate time.Time, tourTrip NullableFPHSpedVAPIObjectsOMSITourTrip, map_ NullableFPHSpedVAPIObjectsOMSIMap, startKM float64, endKM NullableFloat64, visDistance NullableString, value NullableInt32, realtimeBoni NullableFloat64, followupBoni NullableFloat64, tax NullableFloat64, resultValue NullableFloat64, currency NullableString, state FPHSpedVAPIEnumsOMSITaskState, user NullableFPHSpedVAPIObjectsUsersUser, spedition NullableFPHSpedVAPIObjectsSpeditionsSpedition, registeredBusStops []FPHSpedVAPIObjectsOMSIDrivenTripBusStop) *FPHSpedVAPIObjectsOMSIDrivenTrip {
	this := FPHSpedVAPIObjectsOMSIDrivenTrip{}
	this.Id = id
	this.VisibleID = visibleID
	this.StartDate = startDate
	this.EndDate = endDate
	this.NeededTime = neededTime
	this.BaseDate = baseDate
	this.TourTrip = tourTrip
	this.Map = map_
	this.StartKM = startKM
	this.EndKM = endKM
	this.VisDistance = visDistance
	this.Value = value
	this.RealtimeBoni = realtimeBoni
	this.FollowupBoni = followupBoni
	this.Tax = tax
	this.ResultValue = resultValue
	this.Currency = currency
	this.State = state
	this.User = user
	this.Spedition = spedition
	this.RegisteredBusStops = registeredBusStops
	return &this
}

// NewFPHSpedVAPIObjectsOMSIDrivenTripWithDefaults instantiates a new FPHSpedVAPIObjectsOMSIDrivenTrip object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFPHSpedVAPIObjectsOMSIDrivenTripWithDefaults() *FPHSpedVAPIObjectsOMSIDrivenTrip {
	this := FPHSpedVAPIObjectsOMSIDrivenTrip{}
	return &this
}

// GetId returns the Id field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetId(v int32) {
	o.Id = v
}

// GetVisibleID returns the VisibleID field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetVisibleID() string {
	if o == nil || o.VisibleID.Get() == nil {
		var ret string
		return ret
	}

	return *o.VisibleID.Get()
}

// GetVisibleIDOk returns a tuple with the VisibleID field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetVisibleIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VisibleID.Get(), o.VisibleID.IsSet()
}

// SetVisibleID sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetVisibleID(v string) {
	o.VisibleID.Set(&v)
}

// GetStartDate returns the StartDate field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetStartDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetStartDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartDate, true
}

// SetStartDate sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetStartDate(v time.Time) {
	o.StartDate = v
}

// GetEndDate returns the EndDate field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetEndDate() time.Time {
	if o == nil || o.EndDate.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.EndDate.Get()
}

// GetEndDateOk returns a tuple with the EndDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetEndDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDate.Get(), o.EndDate.IsSet()
}

// SetEndDate sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetEndDate(v time.Time) {
	o.EndDate.Set(&v)
}

// GetNeededTime returns the NeededTime field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetNeededTime() string {
	if o == nil || o.NeededTime.Get() == nil {
		var ret string
		return ret
	}

	return *o.NeededTime.Get()
}

// GetNeededTimeOk returns a tuple with the NeededTime field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetNeededTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NeededTime.Get(), o.NeededTime.IsSet()
}

// SetNeededTime sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetNeededTime(v string) {
	o.NeededTime.Set(&v)
}

// GetBaseDate returns the BaseDate field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetBaseDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.BaseDate
}

// GetBaseDateOk returns a tuple with the BaseDate field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetBaseDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseDate, true
}

// SetBaseDate sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetBaseDate(v time.Time) {
	o.BaseDate = v
}

// GetTourTrip returns the TourTrip field value
// If the value is explicit nil, the zero value for FPHSpedVAPIObjectsOMSITourTrip will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetTourTrip() FPHSpedVAPIObjectsOMSITourTrip {
	if o == nil || o.TourTrip.Get() == nil {
		var ret FPHSpedVAPIObjectsOMSITourTrip
		return ret
	}

	return *o.TourTrip.Get()
}

// GetTourTripOk returns a tuple with the TourTrip field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetTourTripOk() (*FPHSpedVAPIObjectsOMSITourTrip, bool) {
	if o == nil {
		return nil, false
	}
	return o.TourTrip.Get(), o.TourTrip.IsSet()
}

// SetTourTrip sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetTourTrip(v FPHSpedVAPIObjectsOMSITourTrip) {
	o.TourTrip.Set(&v)
}

// GetMap returns the Map field value
// If the value is explicit nil, the zero value for FPHSpedVAPIObjectsOMSIMap will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetMap() FPHSpedVAPIObjectsOMSIMap {
	if o == nil || o.Map.Get() == nil {
		var ret FPHSpedVAPIObjectsOMSIMap
		return ret
	}

	return *o.Map.Get()
}

// GetMapOk returns a tuple with the Map field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetMapOk() (*FPHSpedVAPIObjectsOMSIMap, bool) {
	if o == nil {
		return nil, false
	}
	return o.Map.Get(), o.Map.IsSet()
}

// SetMap sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetMap(v FPHSpedVAPIObjectsOMSIMap) {
	o.Map.Set(&v)
}

// GetStartKM returns the StartKM field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetStartKM() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.StartKM
}

// GetStartKMOk returns a tuple with the StartKM field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetStartKMOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartKM, true
}

// SetStartKM sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetStartKM(v float64) {
	o.StartKM = v
}

// GetEndKM returns the EndKM field value
// If the value is explicit nil, the zero value for float64 will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetEndKM() float64 {
	if o == nil || o.EndKM.Get() == nil {
		var ret float64
		return ret
	}

	return *o.EndKM.Get()
}

// GetEndKMOk returns a tuple with the EndKM field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetEndKMOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndKM.Get(), o.EndKM.IsSet()
}

// SetEndKM sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetEndKM(v float64) {
	o.EndKM.Set(&v)
}

// GetVisDistance returns the VisDistance field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetVisDistance() string {
	if o == nil || o.VisDistance.Get() == nil {
		var ret string
		return ret
	}

	return *o.VisDistance.Get()
}

// GetVisDistanceOk returns a tuple with the VisDistance field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetVisDistanceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VisDistance.Get(), o.VisDistance.IsSet()
}

// SetVisDistance sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetVisDistance(v string) {
	o.VisDistance.Set(&v)
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetValue() int32 {
	if o == nil || o.Value.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// SetValue sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetValue(v int32) {
	o.Value.Set(&v)
}

// GetRealtimeBoni returns the RealtimeBoni field value
// If the value is explicit nil, the zero value for float64 will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetRealtimeBoni() float64 {
	if o == nil || o.RealtimeBoni.Get() == nil {
		var ret float64
		return ret
	}

	return *o.RealtimeBoni.Get()
}

// GetRealtimeBoniOk returns a tuple with the RealtimeBoni field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetRealtimeBoniOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.RealtimeBoni.Get(), o.RealtimeBoni.IsSet()
}

// SetRealtimeBoni sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetRealtimeBoni(v float64) {
	o.RealtimeBoni.Set(&v)
}

// GetFollowupBoni returns the FollowupBoni field value
// If the value is explicit nil, the zero value for float64 will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetFollowupBoni() float64 {
	if o == nil || o.FollowupBoni.Get() == nil {
		var ret float64
		return ret
	}

	return *o.FollowupBoni.Get()
}

// GetFollowupBoniOk returns a tuple with the FollowupBoni field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetFollowupBoniOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.FollowupBoni.Get(), o.FollowupBoni.IsSet()
}

// SetFollowupBoni sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetFollowupBoni(v float64) {
	o.FollowupBoni.Set(&v)
}

// GetTax returns the Tax field value
// If the value is explicit nil, the zero value for float64 will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetTax() float64 {
	if o == nil || o.Tax.Get() == nil {
		var ret float64
		return ret
	}

	return *o.Tax.Get()
}

// GetTaxOk returns a tuple with the Tax field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetTaxOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tax.Get(), o.Tax.IsSet()
}

// SetTax sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetTax(v float64) {
	o.Tax.Set(&v)
}

// GetResultValue returns the ResultValue field value
// If the value is explicit nil, the zero value for float64 will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetResultValue() float64 {
	if o == nil || o.ResultValue.Get() == nil {
		var ret float64
		return ret
	}

	return *o.ResultValue.Get()
}

// GetResultValueOk returns a tuple with the ResultValue field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetResultValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultValue.Get(), o.ResultValue.IsSet()
}

// SetResultValue sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetResultValue(v float64) {
	o.ResultValue.Set(&v)
}

// GetCurrency returns the Currency field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetCurrency() string {
	if o == nil || o.Currency.Get() == nil {
		var ret string
		return ret
	}

	return *o.Currency.Get()
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Currency.Get(), o.Currency.IsSet()
}

// SetCurrency sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetCurrency(v string) {
	o.Currency.Set(&v)
}

// GetState returns the State field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetState() FPHSpedVAPIEnumsOMSITaskState {
	if o == nil {
		var ret FPHSpedVAPIEnumsOMSITaskState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetStateOk() (*FPHSpedVAPIEnumsOMSITaskState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetState(v FPHSpedVAPIEnumsOMSITaskState) {
	o.State = v
}

// GetUser returns the User field value
// If the value is explicit nil, the zero value for FPHSpedVAPIObjectsUsersUser will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetUser() FPHSpedVAPIObjectsUsersUser {
	if o == nil || o.User.Get() == nil {
		var ret FPHSpedVAPIObjectsUsersUser
		return ret
	}

	return *o.User.Get()
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetUserOk() (*FPHSpedVAPIObjectsUsersUser, bool) {
	if o == nil {
		return nil, false
	}
	return o.User.Get(), o.User.IsSet()
}

// SetUser sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetUser(v FPHSpedVAPIObjectsUsersUser) {
	o.User.Set(&v)
}

// GetSpedition returns the Spedition field value
// If the value is explicit nil, the zero value for FPHSpedVAPIObjectsSpeditionsSpedition will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetSpedition() FPHSpedVAPIObjectsSpeditionsSpedition {
	if o == nil || o.Spedition.Get() == nil {
		var ret FPHSpedVAPIObjectsSpeditionsSpedition
		return ret
	}

	return *o.Spedition.Get()
}

// GetSpeditionOk returns a tuple with the Spedition field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetSpeditionOk() (*FPHSpedVAPIObjectsSpeditionsSpedition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Spedition.Get(), o.Spedition.IsSet()
}

// SetSpedition sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetSpedition(v FPHSpedVAPIObjectsSpeditionsSpedition) {
	o.Spedition.Set(&v)
}

// GetRegisteredBusStops returns the RegisteredBusStops field value
// If the value is explicit nil, the zero value for []FPHSpedVAPIObjectsOMSIDrivenTripBusStop will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetRegisteredBusStops() []FPHSpedVAPIObjectsOMSIDrivenTripBusStop {
	if o == nil {
		var ret []FPHSpedVAPIObjectsOMSIDrivenTripBusStop
		return ret
	}

	return o.RegisteredBusStops
}

// GetRegisteredBusStopsOk returns a tuple with the RegisteredBusStops field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) GetRegisteredBusStopsOk() ([]FPHSpedVAPIObjectsOMSIDrivenTripBusStop, bool) {
	if o == nil || IsNil(o.RegisteredBusStops) {
		return nil, false
	}
	return o.RegisteredBusStops, true
}

// SetRegisteredBusStops sets field value
func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) SetRegisteredBusStops(v []FPHSpedVAPIObjectsOMSIDrivenTripBusStop) {
	o.RegisteredBusStops = v
}

func (o FPHSpedVAPIObjectsOMSIDrivenTrip) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FPHSpedVAPIObjectsOMSIDrivenTrip) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["visibleID"] = o.VisibleID.Get()
	toSerialize["startDate"] = o.StartDate
	toSerialize["endDate"] = o.EndDate.Get()
	toSerialize["neededTime"] = o.NeededTime.Get()
	toSerialize["baseDate"] = o.BaseDate
	toSerialize["tourTrip"] = o.TourTrip.Get()
	toSerialize["map"] = o.Map.Get()
	toSerialize["startKM"] = o.StartKM
	toSerialize["endKM"] = o.EndKM.Get()
	toSerialize["visDistance"] = o.VisDistance.Get()
	toSerialize["value"] = o.Value.Get()
	toSerialize["realtimeBoni"] = o.RealtimeBoni.Get()
	toSerialize["followupBoni"] = o.FollowupBoni.Get()
	toSerialize["tax"] = o.Tax.Get()
	toSerialize["resultValue"] = o.ResultValue.Get()
	toSerialize["currency"] = o.Currency.Get()
	toSerialize["state"] = o.State
	toSerialize["user"] = o.User.Get()
	toSerialize["spedition"] = o.Spedition.Get()
	if o.RegisteredBusStops != nil {
		toSerialize["registeredBusStops"] = o.RegisteredBusStops
	}
	return toSerialize, nil
}

func (o *FPHSpedVAPIObjectsOMSIDrivenTrip) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"visibleID",
		"startDate",
		"endDate",
		"neededTime",
		"baseDate",
		"tourTrip",
		"map",
		"startKM",
		"endKM",
		"visDistance",
		"value",
		"realtimeBoni",
		"followupBoni",
		"tax",
		"resultValue",
		"currency",
		"state",
		"user",
		"spedition",
		"registeredBusStops",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFPHSpedVAPIObjectsOMSIDrivenTrip := _FPHSpedVAPIObjectsOMSIDrivenTrip{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFPHSpedVAPIObjectsOMSIDrivenTrip)

	if err != nil {
		return err
	}

	*o = FPHSpedVAPIObjectsOMSIDrivenTrip(varFPHSpedVAPIObjectsOMSIDrivenTrip)

	return err
}

type NullableFPHSpedVAPIObjectsOMSIDrivenTrip struct {
	value *FPHSpedVAPIObjectsOMSIDrivenTrip
	isSet bool
}

func (v NullableFPHSpedVAPIObjectsOMSIDrivenTrip) Get() *FPHSpedVAPIObjectsOMSIDrivenTrip {
	return v.value
}

func (v *NullableFPHSpedVAPIObjectsOMSIDrivenTrip) Set(val *FPHSpedVAPIObjectsOMSIDrivenTrip) {
	v.value = val
	v.isSet = true
}

func (v NullableFPHSpedVAPIObjectsOMSIDrivenTrip) IsSet() bool {
	return v.isSet
}

func (v *NullableFPHSpedVAPIObjectsOMSIDrivenTrip) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFPHSpedVAPIObjectsOMSIDrivenTrip(val *FPHSpedVAPIObjectsOMSIDrivenTrip) *NullableFPHSpedVAPIObjectsOMSIDrivenTrip {
	return &NullableFPHSpedVAPIObjectsOMSIDrivenTrip{value: val, isSet: true}
}

func (v NullableFPHSpedVAPIObjectsOMSIDrivenTrip) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFPHSpedVAPIObjectsOMSIDrivenTrip) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


